### ISSUE TITLE
Remove fixed value lists

### ISSUE THREAD

**Issue by kerstarno** [SAA-SDT/eas-schemas#1]
## Creator of issue

1. Kerstin Arnold
2. EAD team lead, TS-EAS
3. @kerstarno
4. kerstin.arnold@archivesportaleurope.net

## The issue relates to

- [ ] EAC-CPF schema issue
- [ ] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [ ] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [x] Suggestions for all schemas
- [x] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature

* Text: Discussing further alignment between the EAS in the context of the EAD revision meetings in Boston and The Hague end of August and beginning of September 2022 has covered `<control>` among other elements to reconfirm that the changes introduced with the release of EAC-CPF 2.0 will also work in the context of EAD. It has been suggested to remove the predefined lists of value for the new attributes @maintenanceStatus, @publicationStatus, @agentType, and @maintenanceEventType and to change their data type to NMTOKEN to allow for any text. The current value lists could still be mentioned in the tag libraries as recommendations, but shouldn't be seen as the only options.

**Comment by kerstarno** [comment]
@fordmadox @karinbredenberg @marieelia

At the EAC team meeting on 1 September, it was decided that this question should be expedited to the whole committee as it will also affect EAF in future. 

(P.S.: I don't seem to be able to add assignees, hence I'm mentioning you all directly.)

**Comment by kerstarno** [comment]
The topic was discussed in a series of EAD team and Schema team meetings in preparation to the the all-committee meeting in February, when four options were presented and compared including example encodings for illustration. Following this meeting, all TS-EAS members were asked to vote for their preferred option. 

The overall preference went to the option that suggested to extend the concept of the `@...Encoding` attributes that already exist in `<control>`, e.g. `@dateEncoding`, and define in one place for the whole EAS XML file which standard or vocabulary is followed to provide - in this case - normalised date information. Adapted to the attributes that currently use predefined value lists in the EAD and EAC-CPF schemas, the intent is to create `@...Encoding` attributes within `<control>` for each of these with the values "EASList" or "other[nameOfTheAttribute]Encoding". This would go hand-in-hand with highly recommending that a definition or reference to a definition of any value lists other than the EAS list is provided within `<conventionDeclaration>`. This would apply to cases when the EAS list is mainly extended by a few local values in the same way as when a completely different list of values is used.

Here is a list of changes resulting from this decision:

- Add the following attributes with these values to `<control>`
  - For EAD and EAC-CPF 
    - @detailLevelEncoding; “EASList”, “otherDetailLevelEncoding”
    - @maintenanceStatusEncoding; “EASList”, “otherMaintenanceStatusEncoding”
    - @publicationStatusEncoding; “EASList”, “otherPublicationStatusEncoding”
    - @maintenanceEventTypeEncoding; “EASList”, “otherMaintenanceEventTypeEncoding”
    - @agentTypeEncoding; “EASList”, “otherAgentTypeEncoding”
    - @audienceEncoding; “EASList”, “otherAudienceEncoding”
    - @addressLineEncoding; “EASList”, “otherAddressLineEncoding”
    - @contactLineEncoding; “EASList”, “otherContactLineEncoding”
    - @statusEncoding; “EASList”, “otherStatusEncoding”
    - @targetTypeEncoding; “EASList”, “otherTargetTypeEncoding”
  - Only for EAD 
    - @coverageEncoding; “EASList”, “otherCoverageEncoding”
    - @daoTypeEncoding; “EASList”, “otherDaoTypeEncoding”
    - @dscTypeEncoding; “EASList”, “otherDscTypeEncoding”
    - @levelEncoding; “EASList”, “otherLevelEncoding”
    - @physDescStructuredTypeEncoding; “EASList”, “otherPhysDescStructuredEncoding”
    - @unitDateTypeEncoding; “EASList”, “otherUnitDateTypeEncoding”
  - Only for EAC-CPF
    - @identityTypeEncoding; “EASList”, “otheridentityTypeEncoding”
- Change the data type for the following attributes to NMTOKEN (following the data type e.g. for `@languageOfElement`)
  - For EAD and EAC-CPF
    - @addressLineType
    - @agentType
    - @audience
    - @contactLineType
    - @detailLevel
    - @maintenanceEventType
    - @maintanceStatus
    - @publicationStatus
    - @status
    - @targetType
  - Only for EAD
    - @coverage
    - @daoType
    - @dscType
    - @level 
    - @physDescStructuredType
    - @unitDateType
   - Only for EAC-CPF
    - @identityType
- Remove `@other...` attributes (only EAD)
  - `@otherLevel` from `<archDesc>` and from numbered and unnumbered `<c>`
  - `@otherDaoType` from `<dao>`
  - `@otherDscType` from `<dsc>`
  - `@otherPhysDescStructuredType` from `<physDescStructured>`
- Remove `@localType` attribute from the following elements (EAD and EAC-CPF)
  - `<addressLine>`
  - `<contactLine>`
  - `<dao>`
  - `<relationEntry>` (note: `<relationEntry>` will be converted to `<targetEntity>`, which has `@targetType`but no `@localType`, so this bullet point is mainly for reference)
-  The **following aspects** are **not decided yet**, but will mostly be discussed at the hybrid meeting in Washington, DC, between 24 and 26 July 2023 
  - Make the following attributes optional
    - Only for EAD
      - `@coverage`
      - `@daoType` 
      - `@physDescStructuredType`
    - For EAD and EAC-CPF
      - `@targetType`
      - `@agentType`
      - `@maintenanceEventType`
      - `@maintenanceStatus`
  - Make `@levelEncoding` within `<control>` mandatory (only EAD)

**Comment by fordmadox** [comment]
Updating now, but a thought:  why don't we simply the otherX options and just provide the following two options for each:  EASList OR other.  We haven't gone the wacky route of suggesting that we include values like "EASListLevelEncoding" so why would need an "otherLevelEncoding" value when "other" will suffice (and be simpler)?

**Comment by fordmadox** [comment]
Also, if we stick with the principle of requiring explicit encoding declarations, then we will at the very least need to require languageEncoding, as well, right? That would be far more important than, say, coverageEncoding.  Right now that attribute is still optional, however, as defined, although the EAD3 schematron and the EAD2002 schema choose different variations of 639-2 as the inferred default option.  Further, It would also seem like scriptEncoding would need to be required, even though that option has less options than languageEncoding and has always had an inferred default value of 15924.

**Comment by fordmadox** [comment]
Another flag to pick up, eventually:  we have a mix of 'token' and 'NMTOKEN'.  Should review.  Ideally we could use 'token' throughout, but there might be attributes that we want to exclude the possibility of whitespace, etc.

**Comment by kerstarno** [comment]
Thanks, Mark. To pick up on your comments:

- I think, with the "other...Encoding" values we mainly stuck to the way that already existed for the attributes relating to the ISO standards. Simply using "other" would, however, minimise the options for any automatic checks if a file that says "other" for a series of `@...Encoding` attributes does include a related `<conventionDeclaration>` element. That is, if we recommend using `<shortCode>` to include the "other...Encoding" value for cross-reference.
- Yes, true, as `@languageCode` would be required if `<languageDeclaration>` is used, we'd probably also need to require `@languageEncoding`. I don't think, we'd need to require `@scriptEncoding`, though, especially not if IETF tags are used and because `@scriptCode` is only optional. That being said, I'd leave it optional for now considering that there is a proposal to be discussed in Washington about actually reversing the occurrence of the related attributes (see #26).
- Good point about token vs NMTOKEN and the need to review this once more. I thought to remember that we've had that conversation in the context of the major revision of EAC-CPF already and that we went for NMTOKEN as the baseline, which is why I suggested it here as well.

**Comment by kerstarno** [comment]
> Another flag to pick up, eventually: we have a mix of 'token' and 'NMTOKEN'. Should review. Ideally we could use 'token' throughout, but there might be attributes that we want to exclude the possibility of whitespace, etc.

See #50

**Comment by kerstarno** [comment]
Note that the related issue #26 has been decided, so that `@maintenanceStatusEncoding`, `@maintenanceEventTypeEncoding`, `@agentTypeEncoding`, `@targetTypeEncoding`, `@coverageEncoding`, `@daoTypeEncoding`, `@levelEncoding`, and `@physDescStructuredTypeEncoding` can be made optional in `<control>`.

**Comment by kerstarno** [comment]
Update (4 January 2024) to the original details from July 2023 (see comment before the previous one)

- [x] **Add the following attributes with these values to `<control>`**
  - [ ] _For EAD and EAC-CPF_ 
    - [ ] `@detailLevelEncoding`; “EASList”, “otherDetailLevelEncoding”
    - [ ] `@maintenanceStatusEncoding`; “EASList”, “otherMaintenanceStatusEncoding”
    - [ ] `@publicationStatusEncoding`; “EASList”, “otherPublicationStatusEncoding”
    - [ ] `@maintenanceEventTypeEncoding`; “EASList”, “otherMaintenanceEventTypeEncoding”
    - [ ] ~~`@agentTypeEncoding`; “EASList”, “otherAgentTypeEncoding”~~
    - [ ] `@audienceEncoding`; “EASList”, “otherAudienceEncoding”
    - [ ] `@addressLineEncoding`; “EASList”, “otherAddressLineEncoding”
    - [ ] `@contactLineEncoding`; “EASList”, “otherContactLineEncoding”
    - [ ] `@statusEncoding`; “EASList”, “otherStatusEncoding”
    - [ ] ~~`@targetTypeEncoding`; “EASList”, “otherTargetTypeEncoding”~~
  - [ ] _Only for EAD_ 
    - [ ] `@coverageEncoding`; “EASList”, “otherCoverageEncoding”
    - [ ] ~~`@daoTypeEncoding`; “EASList”, “otherDaoTypeEncoding”~~
    - [ ] `@dscTypeEncoding`; “EASList”, “otherDscTypeEncoding”
    - [ ] `@levelEncoding`; “EASList”, “otherLevelEncoding”
    - [ ] `@physDescStructuredTypeEncoding`; “EASList”, “otherPhysDescStructuredEncoding”
    - [ ] `@unitDateTypeEncoding`; “EASList”, “otherUnitDateTypeEncoding”
  - [ ] _Only for EAC-CPF_
    - [ ] `@identityTypeEncoding`; “EASList”, “otheridentityTypeEncoding”
- [x] **Change the data type for the following attributes to NMTOKEN (following the data type e.g. for `@languageOfElement`)**
  - [ ] _For EAD and EAC-CPF_
    - [ ] `@addressLineType`
    - [ ] ~~`@agentType`~~
    - [ ] `@audience`
    - [ ] `@contactLineType`
    - [ ] `@detailLevel`
    - [ ] `@maintenanceEventType`
    - [ ] `@maintanceStatus`
    - [ ] `@publicationStatus`
    - [ ] `@status`
    - [ ] ~~`@targetType`~~
  - [ ] _Only for EAD_
    - [ ] `@coverage`
    - [ ] ~~`@daoType`~~
    - [ ] `@dscType`
    - [ ] `@level`
    - [ ] `@physDescStructuredType`
    - [ ] `@unitDateType`
   - [ ] _Only for EAC-CPF_
     - [ ] `@identityType`
- [x] **Remove `@other...` attributes (only EAD)**
  - [ ] `@otherLevel` from `<archDesc>` and from numbered and unnumbered `<c>`
  - [ ] `@otherDaoType` from `<dao>` (note - added new on 4 January 2024: `<dao>` will be incorporated in to the element `<formAvailable>`, see #65, so this bullet point is mainly for reference) 
  - [ ] `@otherDscType` from `<dsc>`
  - [ ] `@otherPhysDescStructuredType` from `<physDescStructured>`
- [x] **Remove `@localType` attribute from the following elements**
  - [ ] _For EAD and EAC-CPF_
    - [ ] `<addressLine>`
    - [ ] `<contactLine>`
  - [ ] _Only for EAD_
    - [ ] `<dao>` (note - added new on 4 January 2024: `<dao>` will be incorporated in to the element `<formAvailable>`, see #65, so this bullet point is mainly for reference) 
    - [ ] `<relationEntry>` (note: `<relationEntry>` will be converted to `<targetEntity>`, which has `<targetType>` but no `@localType`, so this bullet point is mainly for reference)

New changes in addition to the above:
- [ ] **Remove the following attributes again from `<control>`**
  - [ ] _For EAD and EAC-CPF_ 
    - [ ] `@agentTypeEncoding`
    - [ ] `@targetTypeEncoding`
  - [ ] _Only for EAD_ 
    - [ ] `@daoTypeEncoding`
- [ ] **Remove the following attributes**
  - [ ] _For EAD and EAC-CPF_ 
    - [ ] `@agentType` (will now be an element again, see #58)
    - [ ] `@targetType` (will now be an element, see #33)
  - [ ] _Only for EAD_ 
    - [ ] `@daoType` (will be encoded differently in the new element `<formAvailable>`, see #65)

**Comment by karinbredenberg** [comment]
I'm only testing the EAD schema thus the changes being needed for EAC-CPF needs to be tested on its own.

**Comment by karinbredenberg** [comment]
Comments from first testing:
@addressLineEncoding is named @addressTypeLineEncoding in the schemas
@contactLineEncoding is named @contactTypeLineEncoding in the schemas
@maintenanceEventType is needed to be changed to NMTOKEN
@maintanceStatus is needed to be changed to NMTOKEN
@publicationStatus is needed to be changed to NMTOKEN
@status is not updated yet
@dscType not implemented yet
@level not implemented yet
@physDescStructuredType not implemented yet

**Comment by kerstarno** [comment]
Re-tested with XSD and RNG for the changes related to EAD 4.0.

All aspects listed above have been solved with the exception of the attribute `@descriptionOfComponentsType` still missing from `<descriptionOfComponents>`. I have created a pull request for the respective change (#77). Once this pull request has been merged, this issue needs a final round of testing.

**Comment by fordmadox** [comment]
Thanks for the pull request!  Should be test-able again now.  

(That said, if we were to really aim for simplification, I think that reversing the EAD3 decision of having separate 'elementNameType' attributes, and instead having one 'type' attribute, would be the way to go, and is implied already by how attribute nodes are related to the element node).

**Comment by kerstarno** [comment]
Re-tested again with the XSD and the RNG and can confirm that `@descriptionOfComponentsType` is now available with data type "token" but without any predefined values with `<descriptionOfComponents>`.
