### ISSUE TITLE
Align <control> across EAD and EAC-CPF

### ISSUE THREAD

**Issue by kerstarno** [SAA-SDT/eas-schemas#32]
## Creator of issue

1. Kerstin Arnold
2. EAD team lead, TS-EAS
3. @kerstarno
4. kerstin.arnold@archivesportaleurope.net

## The issue relates to

- [x] EAC-CPF schema issue
- [x] EAC-CPF Tag Library issue
- [x] EAD schema issue
- [x] EAD Tag Library issue
- [x] Schema issue
- [x] Tag Library issue
- [x] Suggestions for all schemas
- [x] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature

* Text: `<control>` should be aligned across EAD and EAC-CPF.

**_Note for working on and testing this issue: When the schema changes are done in the respective development branch, please mark the tasks on the highest levels of the list (printed in bold) by ticking the box. When the changes have been tested successfully, please mark the tasks on the lowest level and - if existing - on the mid-level of the list (printed in italics) by ticking the box._**

For EAD this means the following changes need to be applied.
- [x] **For the `<control>` element itself**
  - [x] Remove `<maintenancestatus>` and add `@maintenanceStatus` as ~~required~~ optional attribute (note re data type and values, see #1; note re decision on the attribute's occurrence, see #26) 
  - [x] Remove `<publicationstatus>` and add `@publicationStatus` as optional attribute (same notes as for `@maintenanceStatus`)
  - [x] Remove `<representation>` (see #27)
  - [x] Remove `<filedesc>` (see #27)
  - [x] Remove `<localcontrol>`
  - [x] _Apply camelCasing to these elements:_
    - [x] `<recordId>`
    - [x] `<otherRecordId>`
    - [x] `<maintenanceAgency>`
    - [x] `<languageDeclaration>` 
    - [x] `<conventionDeclaration>`
    - [x] `<rightsDeclaration>`
    - [x] `<localTypeDeclaration>`
    - [x] `<maintenanceHistory>`
  - [x] _Change the order of its subelements to follow design principle of required, not repeatable first to optional, repeatable last, i.e. set the following order:_
    - [x] `<recordId>` (1..1), `<maintenanceAgency>` (1..1), `<maintenanceHistory>` (1..1), `<sources>` (0..1)
    - [x] `<conventionDeclaration>`, `<languageDeclaration>`, `<localTypeDeclaration>`, `<otherRecordId>`, `<rightsDeclaration>` (all 0..n)
  - [x] _Apply camelCasing to these attributes:_
    - [x] `@languageEncoding` (renamed from `@langencoding`)
    - [x] `@scriptEncoding`
    - [x] `@dateEncoding`
    - [x] `@countryEncoding`
    - [x] `@repositoryEncoding`
    - [ ] ~~`@encodingAnalog`~~ (see #37)
    - [ ] ~~`@relatedEncoding`~~ (see #37)
    - [ ] ~~`@altRender`~~ (see #36)
  - [x] Replace `@lang` and `@script` with `@languageOfElement` and `@scriptOfElement` respectively (see #30)
  - [x] Adapt `@audience` (see #1)
  - [x] Add `@target`(see #31)
  - [x] Add `detailLevel` (optional, data type: ~~NMTOKEN~~ token)
  - [x] Add option to include attributes from any other namespace (see #28)
  - [x] _Apply camelCasing to these attribute values:_
    - [x] otherLanguageEncoding (from otherlangencoding) for `@languageEncoding`
    - [x] otherScriptEncoding for `@scriptEncoding`
    - [x] otherDateEncoding for `@dateEncoding`
    - [x] otherCountryEncoding  for `@countryEncoding`
    - [x] otherRepositoryEncoding for `@repositoryEncoding`  
  - [x] Add value "ietf-bcp-47" for `@languageEncoding` 
- [x] **For `<recordId>`**
  - [x] Change content model to require at least one non-whitespace character
  - [x] Replace `@lang` and `@script` with `@languageOfElement` and `@scriptOfElement` respectively
  - [x] Adapt `@audience`
  - [x] Add `@target`
  - [x] Add option to include attributes from any other namespace
  - [x] Remove `@instanceurl` (see #27)
- [x] **For `<otherRecordId>`**
  - [x] Replace `@lang` and `@script` with `@languageOfElement` and `@scriptOfElement` respectively
  - [x] Adapt `@audience`
  - [x] Add `@target`
  - [x] Add option to include attributes from any other namespace
  - [x] Adapt `@localType` to camelCase spelling
  - [x] Add `@localTypeDeclarationReference` (see also #43)
  - [x] Add `@vocabularSource` (optional, data type: token)
  - [x] Add `@vocabularySourceURI` (optional, data type: anyURI)
  - [x] Add `@valueURI` (optional, data type: anyURI)
- [x] **For `<languageDeclaration>`**
  - [x] Remove `<language>` and `<script>`
  - [x] Replace `@lang` and `@script` with `@languageOfElement` and `@scriptOfElement` respectively
  - [x] Adapt `@audience`
  - [x] Add `@target`
  - [x] Add option to include attributes from any other namespace
  - [x] Add `@languageCode` (required, data type: ~~NMTOKEN~~ token)
  - [x] Add `@scriptCode` (optional, data type: ~~NMTOKEN~~ token)
- [x] **For `<conventionDeclaration>`, `<localTypeDeclaration>` and `<rightsDeclaration>`**
  - [x] _Replace `<citation>` with `<reference>` and have `<reference>` as first sub-element (required, not repeatable)_
    - [x] `<reference>` can contain text
    - [x] `<reference>` can contain `<span>` (0..n)
    - [x] `<reference>` can contain `<referringString>` (0..n) (**new**, updated on 5 January 2024)
    - [x] _`<reference>` includes the following optional attributes:_
      - [x] `@audience`
      - [x] `@id`
      - [x] `@target`
      - [x] `@languageOfElement`
      - [x] `@scriptOfElement`
      - [x] `@conventionDeclarationReference`
      - [x] `@maintenanceEventReference`
      - [x] `@sourceReference`
      - [x] `@href`
      - [x] `@linkRole` (adapted from `@linkrole`)
      - [x] `@linkTitle` (adapted from `@linktitle`)   
      - [x] Option to include attributes from any other namespace
  - [x] _Replace `<abbr>` with `<shortCode>` and have `<shortCode>` as second sub-element (optional, not repeatable)_
    - [x] `<shortCode>` can contain text
    - [x] _`<shortCode>` includes the following optional attributes:_
      - [x] `@audience`
      - [x] `@id`
      - [x] `@target`
      - [x] `@languageOfElement`
      - [x] `@scriptOfElement`
      - [x] Option to include attributes from any other namespace
  - [x] Adapt `<descriptiveNote>` to camelCase spelling
  - [x] Replace `@lang` and `@script` with `@languageOfElement` and `@scriptOfElement` respectively
  - [x] Adapt `@audience`
  - [x] Add `@target`
  - [x] Add `@vocabularySource`
  - [x] Add `@vocabularySourceURI`
  - [x] Add `@valueURI`
  - [x] Add option to include attributes from any other namespace
  - [x] No `@localtype` anymore in `<conventionDeclaration>` nor in `<rightsDeclaration>`
- [x] **For `<descriptiveNote>`**
  - [x] Replace `@lang` and `@script` with `@languageOfElement` and `@scriptOfElement` respectively
  - [x] Adapt `@audience`
  - [x] Add `@target`
  - [x] Add `@conventionDeclarationReference`
  - [x] Add `@maintenanceEventReference`
  - [x] Add `@sourceReference`
  - [x] Add option to include attributes from any other namespace 
- [x] **For `<maintenanceHistory>`**
  - [x] Replace `@lang` and `@script` with `@languageOfElement` and `@scriptOfElement` respectively
  - [x] Adapt `@audience`
  - [x] Add `@target`
  - [x] Add option to include attributes from any other namespace 
- [x] **For `<maintenanceEvent>`**
  - [x] Remove `<eventtype>` and add `@maintenanceEventType` as ~~required~~ optional attribute (note re data type and values, see #1; note re decision on the attribute's occurrence, see #26)
  - [x] Remove `<agenttype>` (see details for `<agent>` below)
  - [x] Apply camelCase spelling to `<eventDateTime>` and `<eventDescription>`
  - [x] Change order of sub-elements to start with `<agent>` (1..1), then `<eventDateTime>` (1..1), then `<eventDescription>` (0..n)
  - [x] Replace `@lang` and `@script` with `@languageOfElement` and `@scriptOfElement` respectively
  - [x] Adapt `@audience`
  - [x] Add `@target`
  - [x] Add option to include attributes from any other namespace 
- [x] **For `<agent>`**
  - [ ] ~Add `@agentType` as required attribute (same notes as for `@maintenanceEventType)~
  - [x] Replace `@lang` and `@script` with `@languageOfElement` and `@scriptOfElement` respectively
  - [x] Adapt `@audience`
  - [x] Add `@target`
  - [x] Add `@vocabularySource`
  - [x] Add `@vocabularySourceURI`
  - [x] Add `@valueURI`
  - [x] Allow for the optional attributes `@conventionDeclarationReference`, `@maintenanceEventReference`, and `@sourceReference`
  - [x] Add option to include attributes from any other namespace 
  - [ ] _New changes based on EAD sub-team decision on 15 December 2023 (see also #58)_
    - [x] Remove option for `<agent>` to include text
    - [x] Add `<agentName>` as a required and repeatable sub-element
    - [x] Add `<agentType>` and `<agentRole>` as optional and repeatable sub-elements of `<agent>`
    - [x] Apply the same content model to `<agentName>`, `<agentRole>`, and `<agentType>` by allowing the elements to contain text, by enabling the optional attributes `@audience`, `@id`, `@target`, `@languageOfElement`, `@scriptOfElement`, `@conventionDeclarationReference`, `@maintenanceEventReference`, `@sourceReference`, `@localType`, `@localTypeDeclarationReference`, `@valueURI`, `@vocabularySource`, and `@vocabularySourceURI`, and by allowing for attributes from any other namespace
    - [x] Add `<relationType>` as a sub-element of `<agent>`
    - [x] Allow for the optional sub-elements `<date>`, `<dateRange>`, or `<dateSet>` (choice between these three, not repeatable), `<placeName>` (repeatable), and `<descriptiveNote>` (not repeatable)
    - [ ] Allow for the optional attributes `@localType` and `@localTypeDeclarationReference` with `<agent>` 
- [x] **For `<eventDateTime>`**
  - [x] Replace `@lang` and `@script` with `@languageOfElement` and `@scriptOfElement` respectively
  - [x] Adapt `@audience`
  - [x] Add `@target`
  - [x] Apply camelCase spelling to `@standardDateTime`
  - [x] Remove restrictions from `@standardDateTime` to include any values valid within the date encoding specified
  - [x] Add option to include attributes from any other namespace
- [x] **For `<eventDescription>`**
  - [x] Add `<reference>`(0..n) 
  - [x] Add `<referringString>`(0..n) (**new**, updated on 5 January 2024)
  - [x] Add `<span>`(0..n) 
  - [x] Replace `@lang` and `@script` with `@languageOfElement` and `@scriptOfElement` respectively
  - [x] Adapt `@audience`
  - [x] Add `@target`
  - [x] No `@localtype` anymore in `<eventDescription>`
  - [x] Add option to include attributes from any other namespace
- [x] **For `<sources>`**
  - [x] Add `<descriptiveNote>`(0..1) 
  - [x] Replace `@lang` and `@script` with `@languageOfElement` and `@scriptOfElement` respectively
  - [x] Adapt `@audience`
  - [x] Add `@target`
  - [x] No `@localtype` anymore in `<sources>`
  - [x] Add option to include attributes from any other namespace
- [x] **For `<source>`**
  - [x] Replace `<sourceentry>` with `<reference>`
  - [x] Make `<reference>` required (and repeatable)
  - [x] _Add `<citedRange>` as optional and repeatable (0..n)_
    - [x] `<citedRange>` can contain text
    - [x] _`<citedRange>` includes the following optional attributes:_
      - [x] `@audience`
      - [x] `@id`
      - [x] `@target`
      - [x] `@languageOfElement`
      - [x] `@scriptOfElement`
      - [x] `@conventionDeclarationReference`, `@maintenanceEventReference`, `@sourceReference`
      - [x] `@unit` (data type: token; same as in `<dimensions>`
      - [x] Option to include attributes from any other namespace 
  - [x] Apply camelCase spelling to `<descriptiveNote>`(0..1)  and `<objectXMLWrap>` (0..1)
  - [x] Replace `@lang` and `@script` with `@languageOfElement` and `@scriptOfElement` respectively
  - [x] Adapt `@audience`
  - [x] Add `@target`
  - [x] Add `@vocabularySource`
  - [x] Add `@vocabularySourceURI`
  - [x] Add `@valueURI`
  - [x] Add option to include attributes from any other namespace
  - [x] Remove `@lastdatetimeverified` (see #39)
  - [x] Remove `@actuate`, `@arcrole`, and `@show` (see #41)
- [x] **For `<maintenanceAgency>`**
  - [x] Apply camelCase spelling to `<agencyCode>`, `<agencyName>`, `<otherAgencyCode>`, and `<descriptiveNote>`
  - [x] _Adapt content model so that at least one of `<agencyCode>` or `<agencyName>` has to be present (thereby making `<agencyName>` optional as long as `<agencyCode>` is used_
    - [x] Choice between either `<agencyCode>` (1..1), `<agencyName>` (0..n), `<otherAgencyCode>` (0..n) 
    - [x] Or `<agencyName>` (1..n), `<otherAgencyCode>` (0..n) 
  - [x] Replace `@lang` and `@script` with `@languageOfElement` and `@scriptOfElement` respectively
  - [x] Adapt `@audience`
  - [x] Add `@target`
  - [x] Apply camelCase spelling to `@countryCode`
  - [x] Add `@vocabularySource`
  - [x] Add `@vocabularySourceURI`
  - [x] Add `@valueURI`
  - [x] Add option to include attributes from any other namespace 
- [x] **For `<agencyCode>`, `<agencyName>`, and `<otherAgencyCode>`**
  - [x] Replace `@lang` and `@script` with `@languageOfElement` and `@scriptOfElement` respectively
  - [x] Adapt `@audience`
  - [x] Add `@target`
  - [x] Add `@vocabularySource`
  - [x] Add `@vocabularySourceURI`
  - [x] Add `@valueURI`
  - [x] Add option to include attributes from any other namespace 
  - [x] Add `@status` for `<agencyCode>` and `<otherAgencyCode>` (NOT for `<agencyName>`)
  - [x] No `@localtype` anymore in `<agencyCode>` nor in `<agencyName>`
  - [x] Add `@localTypeDeclarationReference` to `<otherAgencyCode>` (see also #43)

- [x] **General aspects resulting from the changes above:**
These are aspects that are neither mentioned directly above nor in separate issues , but are an effective result of the above.
  - [x] Remove `@value` from EAD 
  - [x] Remove `<titlestmt>`, `<editionstmt>`, `<publicationstmt>`, `<seriesstmt>`, and `<notestmt>` from EAD
  - [x] Remove `<titleproper>`, `<subtitle>`, `<author>`, and `<sponsor>` from EAD
  - [x] Remove `<edition>` from EAD
  - [x] Remove `<publisher>` from EAD
  - [x] Remove `<controlnote>` from EAD
  - [x] Remove `<citation>` from EAD
  - [ ] ~~Remove `<term>` from EAD~~ (Note on 5 January 2024: added again in the context of `<function>`, see #61, and `<subject>`, see #67)
  - [x] Remove `<sourceentry>` from EAD

**_Reference: for EAC-CPF this means the following changes need to be applied at some point in the future._**
- [ ] **For the `<control>` element itself**
  - [ ] Remove `<representation>`
  - [ ] Remove `<localControl>` 
  - [ ] Adapt `<agent>` following the decisions outlined in #58 (and also added above)

**Comment by fordmadox** [comment]
Everything should be ready for testing, minus the changes to EAC-CPF.  I'll get the process set up for EAC in early 2024.

**Comment by kerstarno** [comment]
Adding this here for now as reference regarding changes to `<agent>` that would need to be filtered through to EAC-CPF:

- Add the optional attributes `@conventionDeclarationReference`, `@maintenanceEventReference`, `@sourceReference`,  `@localType`, and `@localTypeDeclarationReference`
- Change `@agentType` back to `<agentType>` as a new optional and repeatable sub-element of `<agent>`
- Add `<agentName>` as a required and repeatable sub-element of `<agent>` and don't allow `<agent>` to contain text anymore
- Add `<agentRole>` as a new optional and repeatable sub-element of `<agent>`
- Add `<date>`, `<dateRange>`, or `<dateSet>` (choice of one of the three), `<placeName>`, and `<descriptiveNote>`, plus `<relationType>` as optional sub-elements of `<agent>`
- Apply the same content model to `<agentName>`, `<agentRole>`, and `<agentType>` by allowing the elements to contain text, by enabling the optional attributes `@audience`, `@id`, `@target`, `@languageOfElement`, `@scriptOfElement`, `@conventionDeclarationReference`, `@maintenanceEventReference`, `@sourceReference`, `@localType`, `@localTypeDeclarationReference`, `@valueURI`, `@vocabularySource`, and `@vocabularySourceURI`, and by allowing for attributes from any other namespace

**Comment by kerstarno** [comment]
Tested with the XSD and the RNG. The following requires further changes (mostly based on additional decisions taken since this issue was originally created):

- `<agent>` has been adapted correctly as per the original description; any additional changes resulting from the relations decision in December have been checked off here as well, but will be reported back officially in #58
- `@status` with `<agencyCode>` and `<otherAgencyCode>` should simply be of data type "token", but not have predefined values anymore (same for any other places, where `@status` is used, see #1)
- camelCase spelling for "other**D**escriptionOfComponentsTypeEncoding" needs to be corrected (the "d" is currently a small letter)

**Comment by fordmadox** [comment]
Merged both pull requests -- thanks!  I've put this back in the "Ready for testing" category.

**Comment by kerstarno** [comment]
Re-tested with the XSD and the RNG and can confirm that:

- `@status` with `<agencyCode>` and `<otherAgencyCode>` is now simply of data type "token" and does not include any predefined values anymore
- camelCase spelling has been applied to the attribute value  "otherDescriptionOfComponentsTypeEncoding"
