### ISSUE TITLE
Align <relations> across EAD and EAC-CPF

### ISSUE THREAD

**Issue by kerstarno** [SAA-SDT/eas-schemas#33]
## Creator of issue

1. Kerstin Arnold
2. EAD team lead, TS-EAS
3. @kerstarno
4. kerstin.arnold@archivesportaleurope.net

## The issue relates to

- [ ] EAC-CPF schema issue
- [ ] EAC-CPF Tag Library issue
- [x] EAD schema issue
- [x] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature

* Text: 

**_Note for working on and testing this issue: When the schema changes are done in development branch, please mark this by ticking the box on the higher level of the list (printed in bold); once the changes have been tested successfully please mark this by ticking the box on the lower levels of the list and - if applicable - the intermediate levels (printed in italics)._**

- [x] **`<relations>`**
  - [x] Add `<descriptiveNote>`
  - [x] Adapt `@audience`
  - [x] Add `@target` (optional, data type: IDREFS)
  - [x] Rename `@lang` and `@script`to `@languageOfElement` and `@scriptOfElement` respectively (both optional, data type: ~~NMTOKEN~~ token)
  - [x] Remove `@localtype`
  - [x] Add `@conventionDeclarationReference`, `@maintenanceEventReference`, and `@sourceReference` (all optional, data type: IDREFS)
  - [x] Add an option to include attributes from any other namespace
- [x] **`<relation>`**
  - [x] _Remove `<relationentry>` and add `<targetEntity>` instead_
    - [x] Make `<targetEntity>` required and not repeatable (note for future conversion: `<relationentry>` was repeatable and allowed for `@localtype`)
    - [x] Have `<targetEntity>` require at least one `<part>` sub-element
    - [ ] ~Have `<targetEntity` require the attribute `@targetType` (see #1 and #26)~
    - [x] _Allow for the following attributes in `<targetEntity>`_
      - [x] `@audience`
      - [x] `@id`
      - [x] `@target`
      - [x] `@languageOfElement`
      - [x] `@scriptOfElement`
      - [x] `@valueURI`
      - [x] `@vocabularySoure`
      - [x] `@vocabularySourceURI`
      - [x] `@conventionDeclarationReference`
      - [x] `@maintenanceEventReference`
      - [x] `@sourceReference`
      - [x] An option to include attributes from any other namespace
  - [x] Apply camelCase spelling to `<objectXMLWrap>`, `<descriptiveNote>`, `<dateRange>` and `<dateSet>`
  - [x] Replace `<datesingle>` with `<date>` (see also #4)
  - [x] Replace `<geogname>` with `<place>` and make it optional and repeatable (see #42)
  - [x] Remove `@relationtype` and `@otherrelationtype`
  - [x] _Add `<targetType>` as optional and repeatable_ 
    - [x] Allow text in `<targetType>`
    - [x] Allow `@audience`, `@id`, `@target`, `@languageOfElement` and `@scriptOfElement` in `<targetType>`
    - [x] Allow `@valueURI`, `@vocabularySoure`, and `@vocabularySourceURI` in `<targetType>`
    - [x] Allow `@conventionDeclarationReference`, `@maintenanceEventReference`, and `@sourceReference` in `<targetType>`
    - [x] Allow `@localType` and `@localTypeDeclarationReference`in `<targetType>`
    - [x] Allow an option to include attributes from any other namespace in `<targetType>`
  - [x] _Add `<relationType>` as optional and repeatable_ 
    - [x] Allow text in `<relationType>`
    - [x] Allow `@audience`, `@id`, `@target`, `@languageOfElement` and `@scriptOfElement` in `<relationType>`
    - [x] Allow `@valueURI`, `@vocabularySoure`, and `@vocabularySourceURI` in `<relationType>`
    - [x] Allow `@conventionDeclarationReference`, `@maintenanceEventReference`, and `@sourceReference` in `<relationType>`
    - [x] Allow `@localType` and `@localTypeDeclarationReference`in `<relationType>`
    - [x] Allow an option to include attributes from any other namespace in `<relationType>`
  - [x] _Add `<targetRole>` as optional and repeatable_ 
    - [x] Allow text in `<targetRole>`
    - [x] Allow `@audience`, `@id`, `@target`, `@languageOfElement` and `@scriptOfElement` in `<targetRole>`
    - [x] Allow `@valueURI`, `@vocabularySoure`, and `@vocabularySourceURI` in `<targetRole>`
    - [x] Allow `@conventionDeclarationReference`, `@maintenanceEventReference`, and `@sourceReference` in `<targetRole>`
    - [x] Allow `@localType` and `@localTypeDeclarationReference`in `<targetRole>`
    - [x] Allow an option to include attributes from any other namespace in `<targetRole>`
  - [x] Adapt `@audience`
  - [x] Add `@target` (optional, data type: IDREFS)
  - [x] Rename `@lang` and `@script`to `@languageOfElement` and `@scriptOfElement` respectively (both optional, data type: ~~NMTOKEN~~ token)
  - [x] Remove linking attributes (`@href`, `@linkrole`, `@linktitle`; `@actuate`, `@arcrole`, `@show`, for the last three see also #41)
  - [x] Remove `@lastdatetimeverified` (see #39)
  - [x] Add `@conventionDeclarationReference`, `@maintenanceEventReference`, and `@sourceReference` (all optional, data type: IDREFS)
  - [x] Add an option to include attributes from any other namespace

**Comment by fordmadox** [comment]
Is the summary that everything is the same as EAC-CPF 2.0, save the addition of a targetRole element (which is modeled exactly the same as relationType)?

**Comment by kerstarno** [comment]
> Is the summary that everything is the same as EAC-CPF 2.0, save the addition of a targetRole element (which is modeled exactly the same as relationType)?

Yes, it's the same as in EAC-CPF 2.0, save the addition of the `<targetType>` element instead of the `@targetType` attribute. `<targetType>` is modelled the same as `<relationType>`. 

`<targetRole>` already exists as an element in the EAC-CPF 2.0 definition.

**Comment by kerstarno** [comment]
Tested with the XSD and the RNG and can confirm that the changes as described above have been implemented.
