### ISSUE TITLE
Remove @transliteration from EAD

### ISSUE THREAD

**Issue by kerstarno** [SAA-SDT/eas-schemas#34]
## Creator of issue

1. Kerstin Arnold
2. EAD team lead, TS-EAS
3. @kerstarno
4. kerstin.arnold@archivesportaleurope.net

## The issue relates to

- [ ] EAC-CPF schema issue
- [ ] EAC-CPF Tag Library issue
- [x] EAD schema issue
- [x] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature

* Text: Remove`@transliteration`. The transliteration scheme used should be specified in `<conventionDeclaration>`, which would then be referred to via `@conventionDeclarationReference` in the respective element.

- [ ] Remove `@transliteration` from `<term>` (only used within `<localControl>` in EAD, which is removed in general, see #32)
- [ ] Remove `@transliteration` from `<sourceentry>` (which is replaced by `<reference>`, see #32)
- [ ] Remove `@transliteration` from `<relationentry>` (which is replaced by `<targetEntity>`, see #33)

_**Note for working on and testing this issue: When the schema changes are done in development branch, please add a comment to this issue; once the changes has been tested successfully please mark this by ticking the box.**_

**Comment by kerstarno** [comment]
Tested successfully. Neither the XSD, nor the RNG include `@transliteration` anymore. The elements `<term>`, `<sourceentry>`, and `<relationentry>` don't exist anymore either. `<reference>`, which in this case replaces `<sourceentry>`, and `<targetEntity>`, which in this case replaces `<relationentry>`, both allow for the new attribute `@conventionDeclarationReference`, via which they can be connected to a `<conventionDeclaration>` that provides the information about transcription/transliteration rules applied.
