### ISSUE TITLE
Update the modelling of languages in EAD to align with EAC-CPF

### ISSUE THREAD

**Issue by kerstarno** [SAA-SDT/eas-schemas#38]
## Creator of issue

1. Kerstin Arnold
2. EAD team lead, TS-EAS
3. @kerstarno
4. kerstin.arnold@archivesportaleurope.net

## The issue relates to

- [ ] EAC-CPF schema issue
- [ ] EAC-CPF Tag Library issue
- [x] EAD schema issue
- [x] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature

* Text: Update the modelling of languages in `<languageDeclaration>` and in `<langmaterial>` to align with EAC-CPF.

**_Note for working on and testing this issue: When the schema changes are done in the respective development branch, please mark the tasks on the highest levels of the list (printed in bold) by ticking the box. When the changes have been tested successfully, please mark the tasks on the lowest level by ticking the box._**

- [x] **For `<languageDeclaration>` see #32**
- [x] **For `<language>`**
  - [x] Adapt `@audience` (see #1)
  - [x] Rename `@lang` and `@script` to `@languageOfElement` and `@scriptOfElement` respectively (see #30)
  - [x] Add `@target` (see #31) (optional)
  - [x] Add `@conventionDeclarationReference`, `@maintenanceEventReference`, `@sourceReference` (see #11) (optional)
  - [x] Rename `@langcode` to `@languageCode`
  - [x] Add option to include attributes from any other namespace (see #28) 
  - [x] Remove `@altrender`, `@encodinganalog`, and `@label`
- [x] **For `<languageset>`**
  - [x] Apply camelCasing and rename to `<languageSet>`
  - [x] Replace `<script>` with `<writingSystem>`
  - [x] Adapt `@audience` (see #1)
  - [x] Rename `@lang` and `@script` to `@languageOfElement` and `@scriptOfElement` respectively (see #30)
  - [x] Add `@target` (see #31) (optional)
  - [x] Add option to include attributes from any other namespace (see #28) 
- [x] **Remove `<script>` and add `<writingSystem>`**
  - [x] _`<writingSystem>`..._
    - [x] Can have text
    - [x] Includes `@audience` (optional)
    - [x] Includes `@id` (optional)
    - [x] Includes `@target` (optional)
    - [x] Includes `@languageOfElement` (optional), changed from `@lang` in `<script>`
    - [x] Includes `@scriptOfElement` (optional), changed from `@script` in `<script>` 
    - [x] Includes `@maintenanceEventReference` (optional)
    - [x] Includes `@sourceReference` (optional)
    - [x] Includes `@conventionDeclarationReference` (optional)
    - [x] Includes `@scriptCode` (optional), changed from `@scriptcode` in `<script>`
    - [x] Can include attributes from any other namespace
    - [x] Does not include `@encodinganalog` nor `@label` anymore

**Comment by fordmadox** [comment]
Should be ready to test, though I haven't looked at this in a while.

**Comment by deletedname** [comment]
All but _Add option to include attributes from any other namespace_ worked in testing. Issue #28 is labeled "Needs work". Some notes:
- In EAD, <language> is a sub-element of <langMaterial>. In EAC-CPF, <language> is a sub-element of <languageUsed>
- The following attributes require a defined `@id` to successfully validate: `@conventionDeclarationReference`, `@maintenanceEventReference`, `@sourceReference` and `@target`.

**Comment by kerstarno** [comment]
@deletedname - 
Hi Iris, just picking up on the question around testing for the attributes from other namespaces. The following works with my Oxygen version 20, so hopefully it'll work with your older version as well:
- I tend to use the XLink namespace for testing this
- For the XSD schema testing, I add `@xmlns:xlink="http://www.w3.org/1999/xlink"` to `<ead>` and I include `"http://www.w3.org/1999/xlink http://www.loc.gov/standards/xlink/xlink.xsd"` into the `@xsi:schemaLocation` attribute that already holds the EAD4 schema location
  - Then I am able to e.g. add `@xlink:href=""` to any element and the file still validates (note that the attribute doesn't actually need to have a value)
- For the RNG schema testing, I add the reference to the XLink namespace directly to the element that I want to check, i.e. I add `@xmlns:xlink="http://www.w3.org/1999/xlink"` and then `@xlink:href=""` for example to the `<language>` element
  - Again, the file still validates

**Comment by deletedname** [comment]
Thank you @kerstarno! The RNG and XSD files have been tested successfully.
