### ISSUE TITLE
Replace <ref> with <reference> and adapt content model

### ISSUE THREAD

**Issue by kerstarno** [SAA-SDT/eas-schemas#40]
## Creator of issue

1. Kerstin Arnold
2. EAD team lead, TS-EAS
3. @kerstarno
4. kerstin.arnold@archivesportaleurope.net

## The issue relates to

- [ ] EAC-CPF schema issue
- [ ] EAC-CPF Tag Library issue
- [x] EAD schema issue
- [x] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature

* Text: Replace `<ref>` with `<reference>` and adapt content model    

**Update (5 January 2024):
Following the EAD team's meeting on 15 December and in relation to the changes suggested especially with #62 and #63, the details of this issue have been updated. The current development version of the schema might still represent what was outlined initially, while further changes might be necessary and require another round of testing.**

**_Note for working on and testing this issue: When the schema changes are done in development branch, please mark this by ticking the box for the higher level in the list (printed in bold); once the changes have been tested successfully please mark this by ticking the box on the lower and intermediate (printed in italics) levels._**

- [x] **Remove `<ref>` from**
  - [ ] _m.refs group_
    - [ ] ~~Used in `<indexEntry>`~~ (see #67)
    - [ ] ~~Used in `<ptrGroup>`~~ (see #67)
  - [x] _m.mixed.basic.elements / m.mixed.basic group and any groups that include it (note that the list below already excludes elements that were to be removed from EAD early on, while those whose removal was decided later on have now been struck through)_
    - [x] Used in `<abstract>`
    - [x] Used in `<container>`
    - [x] Used in `<identificationDataNote>`
    - [x] Used in `<materialSpec>`
    - [x] Used in `<physDesc>`
    - [x] Used in `<physLoc>`
    - [x] Used in `<unitTitle>`
    - [x] Used in `<unitDate>`
    - [x] Used in `<unitId>`
    - [x] Used in `<part>`
    - [x] Used in `<dimensions>`
    - [x] Used in `<physFacet>`
    - [x] Used in `<addressLine>`
    - [ ] ~~Used in `<archRef>`~~ (see #46) 
    - [ ] ~~Used in `<bibRef>`~~ (see #46)
    - [x] Used in `<head>`
    - [x] Used in `<date>` (see also #4)
    - [ ] ~~Used in `<emph>`~~ (see #63)
    - [ ] ~~Used in `<num>`~~ (see #63)
    - [ ] ~~Used in `<quote>`~~ (see #63)
    - [x] Used in `<fromDate>`
    - [x] Used in `<toDate>`
    - [x] Used in `<p>`
    - [ ] ~~Used in `<event>`~~ (see #62)
    - [ ] ~~Used in `<item>`~~ (see #62)
    - [ ] ~~Used in `<entry>`~~ (see #62)
- [x] **Add `<reference>` to**
  - [ ] ~~`<indexEntry>`~~ (see #67)
  - [ ] ~~`<ptrGroup>`~~ (see #67)
  - [x] `<abstract>`
  - [x] `<container>`
  - [ ] ~~`<identificationDataNote>`~~ (see #63)
  - [x] `<materialSpec>`
  - [x] `<physDesc>`
  - [x] `<physLoc>`
  - [x] `<unitTitle>`
  - [x] `<unitDate>`
  - [x] `<unitId>`
  - [x] `<dimensions>`
  - [x] `<physFacet>`
  - [ ] ~~`<archRef>`~~ (see #46)
  - [ ] ~~`<bibRef>`~~ (see #46)
  - [ ] `<head>`
  - [ ] ~~`<emph>`~~ (see #63)
  - [ ] ~~`<num>`~~ (see #63)
  - [ ] ~~`<quote>`~~ (see #63)
  - [x] `<p>`
  - [ ] ~~`<event>`~~ (see #62)
  - [ ] ~~`<item>`~~ (see #62)
  - [ ] ~~`<entry>`~~ (see #62)
- [x] **Changes from `<ref>` to `<reference>`**
  - [x] Remove the optional sub-elements `<abbr>`, `<emph>`, `<expan>`, `<foreign>`, `<lb>`, and `<ptr>`
  - [x] Remove the optional sub-elements `<date>`, `<footnote>`, `<num>`, `<quote>`
  - [x] Remove the optional sub-elements `<persname>`, `<corpname>`, `<famname>`, `<geogname>`, `<name>`, `<occupation>`, `<subject>`, `<genreform>`, `<function>`, and `<title>`
  - [x] Add the optional and repeatable sub-element `<span>`
  - [x] _Newly added (5 January 2024):_ Add the optional and repeatable sub-element `<referringString>`
  - [x] Adapt `@audience`
  - [x] Adapt  data type of `@target` (optional, data type now: IDREFS)
  - [x] Rename `@lang` and `@script`to `@languageOfElement` and `@scriptOfElement` respectively (both optional, data type: ~~NMTOKEN~~ token)
  - [x] Add `@conventionDeclarationReference`, `@maintenanceEventReference`, and `@sourceReference` (all optional, data type: IDREFS)
  - [x] Remove `@actuate`, `@arcrole`, and `@show`
  - [x] Apply camelCase spelling to `@linkRole` and `@linkTitle`
  - [x] Add an option to include attributes from any other namespace
  - [x] For `@entityRef` and `@xPointer` see #45

**Comment by kerstarno** [comment]
Just adding this here as I came across it while testing `<control>`: `<reference>` currently still includes `@entityref` [sic], which should be removed.

**Comment by kerstarno** [comment]
Tested with the XSD and the RNG and can confirm that the above has been implemented as expected apart from the change for `<head>`, which is, however, already reported in #62 (and has been taken care of in the related pull request). Hence I will mark this issue here as "Tested successfully".

The attribute `@entityref` has been removed from `<reference>` in the meantime.
