### ISSUE TITLE
Point to including attributes from other namespaces for encoding the behaviour of a link

### ISSUE THREAD

**Issue by kerstarno** [SAA-SDT/eas-schemas#41]
## Creator of issue

1. Kerstin Arnold
2. EAD team lead, TS-EAS
3. @kerstarno
4. kerstin.arnold@archivesportaleurope.net

## The issue relates to

- [ ] EAC-CPF schema issue
- [ ] EAC-CPF Tag Library issue
- [x] EAD schema issue
- [x] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature

* Text: EAD3 removed the Xlink namespace from the EAD schema, but kept the "EAD version" of the former Xlink attributes mostly as they were. The aim of this issue here is to make things more explicit and to move towards an EAD that concentrates on descriptive information (as part of the EAD schema) and less on how that information is formatted and displayed. Having introduced the option to include attributes from other namespaces (https://github.com/SAA-SDT/eas-schemas/issues/28), it will, however, still be possible to use attributes such as `@xlink:actuate` or `@xlink:show` locally if wanted.
* Resulting change: remove `@actuate`, `@arcrole`, and `@show`    

**_Note for working on and testing this issue: When the schema changes are done in development branch, please mark this by ticking the box for the higher level in the list (printed in bold); once the changes have been tested successfully please mark this by ticking the box._**

- [x] **Remove `@actuate`, `@arcrole`, and `@show` from**
  - [x] `<source>` (aligned with EAC-CPF, #32)
  - [x] `<dao>`
  - [x] `<relation>` (aligned with EAC-CPF, #33)
  - [x] `<ptr>`
  - [x] `<ref>` (changed to `<reference>` and aligned with EAC-CPF, #40)
  - [x] `<footnote>` (only `@actuate` and `@show`, `@arcrole` not used anyway)

**Comment by fordmadox** [comment]
All done, since never added to the new schema pipeline 😃

**Comment by kerstarno** [comment]
Tested successfully with the XSD and RNG. Neither includes `@actuate`, `@arcrole`, or `@show` anymore. Not in the elements mentioned above, nor in any other element. All elements mentioned above instead include an option to add attributes from any other namespaces. 

Should there be the intent to encode different behaviours of links directly in EAD rather than having a default behaviour for links defined via a CSS of the application to display the information, the original XLink versions of these three attributes could be used.
