### ISSUE TITLE
Align the modelling of places and place names across EAD and EAC-CPF

### ISSUE THREAD

**Issue by kerstarno** [SAA-SDT/eas-schemas#42]
## Creator of issue

1. Kerstin Arnold
2. EAD team lead, TS-EAS
3. @kerstarno
4. kerstin.arnold@archivesportaleurope.net

## The issue relates to

- [x] EAC-CPF schema issue
- [x] EAC-CPF Tag Library issue
- [x] EAD schema issue
- [x] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature

* Text: Align the encoding of places and place names with EAC-CPF.

**Update (5 January 2024):
Following the EAD team's meeting on 15 December and the wider conversations on element representing related entities, the details of this issue have been updated (see the end of the task list). The current development version of the schema still represents what was outlined initially, while further changes will be necessary and might require another round of testing.**

**_Note for working on and testing this issue: When the schema changes are done in development branch, please mark this by ticking the box on the higher level of the list (printed in bold); once the changes have been tested successfully please mark this by ticking the box on the lower levels of the list and - if applicable - the intermediate levels (printed in italics)._**

- [x] **Add `<place>` to EAD (following the content model set up in EAC-CPF)**
  - [x] _Require `<place>` to have at least one of these elements (all repeatable)_
    - [x] `<placeName>` (adapted from `<geogname>`)
    - [x] `<placeRole>` (new to EAD)
    - [x] `<geographicCoordinates>` (aligned with EAC-CPF)
    - [x] `<address>` (aligned with EAC-CPF)
    - [x] `<contact>` (new)
  - [x] _Allow for one of these elements within `<place>` (not repeatable)_
    - [x] `<date>`
    - [x] `<dateRange>`
    - [x] `<dateSet>`
  - [x] Have `<descriptiveNote>` as optional and not repeatable in `<place>`
  - [x] _Allow for the following optional attributes in `<place>`_
    - [x] `@audience`
    - [x] `@id`
    - [x] `@target`
    - [x] `@languageOfElement`
    - [x] `@scriptOfElement`
    - [x] `@localType`
    - [x] `@localTypeDeclarationReference`
    - [x] `@vocabularySource`
    - [x] `@vocabularySourceURI`
    - [x] `@valueURI`
    - [x] `@maintenanceEventReference`
    - [x] `@sourceReference`
    - [x] `@conventionDeclarationReference`
    - [x] An option to include attributes from any other namespaces
- [x] **Changes for the definition of `<placeName>` compared to `<geogname>`**
  - [x]  Remove `<part>`
  - [x] Remove `<geographiccoordinates>` (becomes sibling element)
  - [x] Adapt `@audience`
  - [x] Add `@target` (optional, data type: IDREFS)
  - [x] Rename `@lang` and `@script`to `@languageOfElement` and `@scriptOfElement` respectively (both optional, data type: ~~NMTOKEN~~ token)
  - [x] Add `@conventionDeclarationReference`, `@maintenanceEventReference`, and `@sourceReference` (all optional, data type: IDREFS)
  - [x] Apply camelCase spelling to `@localType`
  - [x] Add `@localTypeDeclarationReference` (optional, data type: IDREFS)
  - [x] Replace `@source` with `@vocabularySource` (data type remains token) (see #13, also for the five following points)
  - [x] Add `@vocabularySourceURI` (optional, data type: anyURI)
  - [x] Replace `@identifier` with `@valueURI` (data type changes from token to anyURI)
  - [x] Remove `@rules` (functionality will now be taken on by `@conventionDeclarationReference` and specifying the rules in `<conventionDeclaration>`)
  - [x] Remove `@normal` (as the connection to controlled vocabularies is strengthened, any normalised form of the term(s) used should be retrievable via the new vocabulary and value attributes)
  - [x] Remove `@relator` (the relationship between the place and the materials being described will be given in `<placeRole>`, which is a new sibling element to `<placeName>`)
  - [x] Add an option to include attributes from any other namespace
- [x] **Add `<placeRole>` to EAD**
  - [x] `<placeRole>` can contain text
  - [x] May include `@audience`
  - [x] May include `@id`
  - [x] May include `@target`
  - [x] May include `@languageOfElement`
  - [x] May include `@scriptOfElement`
  - [x] May include `@vocabularySource`
  - [x] May include `@vocabularySourceURI`
  - [x] May include `@valueURI`
  - [x] May include `@maintenanceEventReference`
  - [x] May include `@sourceReference`
  - [x] May include `@conventionDeclarationReference`
  - [x] May include an option to include attributes from any other namespaces
- [x] **Align `<geographicCoordinates>` with EAC-CPF**
  - [x] Apply camelCase spelling
  - [x] Adapt `@audience`
  - [x] Add `@target`
  - [x] Rename `@lang` and `@script`to `@languageOfElement` and `@scriptOfElement` respectively
  - [x] Add `@conventionDeclarationReference`, `@maintenanceEventReference`, and `@sourceReference`
  - [x] Apply camelCase spelling to `@coordinateSystem` (still required)
  - [x] Add an option to include attributes from any other namespace 
- [x] **Align `<address>` with EAC-CPF**
  - [x] Apply camelCase spelling to `<addressLine>` (still required and repeatable)
  - [x] Adapt `@audience`
  - [x] Add `@target`
  - [x] Rename `@lang` and `@script`to `@languageOfElement` and `@scriptOfElement` respectively
  - [x] Add `@conventionDeclarationReference`, `@maintenanceEventReference`, and `@sourceReference`
  - [x] Add `@localType` and `@localTypeDeclarationReference` 
  - [x] Add an option to include attributes from any other namespace 
  - [x] _Align `<addressLine>` with EAC-CPF_
    - [x] Remove `<abbr>`, `<emph>`, `<expan>`, `<foreign>`, `<lb>`, `<ptr>`, `<ref>`
    - [x] Adapt `@audience`
    - [x] Add `@target`
    - [x] Rename `@lang` and `@script`to `@languageOfElement` and `@scriptOfElement` respectively
    - [x] Add `@conventionDeclarationReference`, `@maintenanceEventReference`, and `@sourceReference`
    - [x] Add `@addressLineType`
    - [x] Remove `@localtype` (see #1) 
    - [x] Add an option to include attributes from any other namespace
- [x] **Add `<contact>` to EAD**
  - [x] Requires one or more `<contactLine>` sub-elements
  - [x] May include `@audience`
  - [x] May include `@id`
  - [x] May include `@target`
  - [x] May include `@languageOfElement`
  - [x] May include `@scriptOfElement`
  - [x] May include `@maintenanceEventReference`
  - [x] May include `@sourceReference`
  - [x] May include `@conventionDeclarationReference`
  - [x] May include `@localType`
  - [x] May include `@localTypeDeclarationReference`  
  - [x] May include an option to include attributes from any other namespaces 
  - [x] _Add `<contactLine>` to EAD_
    - [x] `<contactLine>` can contain text
    - [x] May include `@contactLineType`
    - [x] May include `@audience`
    - [x] May include `@id`
    - [x] May include `@target`
    - [x] May include `@languageOfElement`
    - [x] May include `@scriptOfElement`
    - [x] May include `@href`
    - [x] May include `@linkRole`
    - [x] May include `@linkTitle`
    - [x] May include `@maintenanceEventReference`
    - [x] May include `@sourceReference`
    - [x] May include `@conventionDeclarationReference`
    - [x] May include an option to include attributes from any other namespaces
- [x] **Replace `<geogname>` with the broader `<place>` in**
  - [ ] ~~`<chronItem>` (alignment with EAC-CPF)~~ (#62)
  - [ ] ~~`<chronItemSet>` (alignment with EAC-CPF)~~ (#62)
  - [x] `<relation>` (alignment with EAC-CPF) 
- [ ] **Replace `<address>` with the broader `<place>` in** 
  - [ ] ~~`<repository>`~~ (#58)
- [x] **Remove `<geogname>` from**
  - [x] `<ref>` (now `<reference>`, see #40)
- [ ] **Replace `<geogname>` with `<placeName>` in**
  - [ ] ~~`<controlAccess>`~~ (#67)
  - [ ] ~~`<indexEntry>`~~ (#67)
  - [ ] ~~`<nameGrp>`~~ (#67)
  - [ ] ~~`<archRef>`~~ (#46)
  - [ ] ~~`<bibRef>`~~ (#46)
  - [ ] ~~`<physFacet>`~~ (#63)
  - [ ] ~~`<unitTitle>`~~ (#63)
  - [ ] ~~`<abstract>`~~ (see #47, also for the following four elements)
  - [ ] ~~`<p>`~~
  - [ ] ~~`<item>`~~
  - [ ] ~~`<event>`~~
  - [ ] ~~`<entry>`~~

_**New (5 January 2024)**_
- [x] **Add a new `<placeType>` element, make it an optional and repeatable sub-element of `<place>` and include it in the choice group along with `<placeName>`, `<placeRole>`, `<geographicCoordinates>`, `<address>`, and `<contact>`**
  - [x] `<placeType>` can contain text
  - [x] May include `@audience`
  - [x] May include `@id`
  - [x] May include `@target`
  - [x] May include `@languageOfElement`
  - [x] May include `@scriptOfElement`
  - [x] May include `@vocabularySource`
  - [x] May include `@vocabularySourceURI`
  - [x] May include `@valueURI`
  - [x] May include `@maintenanceEventReference`
  - [x] May include `@sourceReference`
  - [x] May include `@conventionDeclarationReference`
  - [x] May include an option to include attributes from any other namespaces
- [x] Add `<relationType>` (see definition in #33) as an optional and repeatable sub-element of `<place>`, though not included in the "one of five"-choice with `<placeName>`, `<placeRole>`, `<geographicCoordinates>`, `<address>`, and `<contact>`

**Comment by kerstarno** [comment]
@fordmadox - Just flagging that this issue has been extended with further changes resulting from the EAD sub-team's meeting on 15 December. 

@marieelia - These latest additions would be chances that should then also be reflected in EAC-CPF at a later point. As it is the addition of further optional sub-elements, I've currently categorised these as minor revision.

**Comment by fordmadox** [comment]
@kerstarno I think it would be easiest to have separate tickets for the changes (from EAC-CPF 2) that are required at this point, since many of the data models where these place elements are listed on the checklists are now no more (e.g., chronItem).  I can take a shot at adding the new placeType element, though, along with re-purposing relationType outside of relation.  Once I've done that, this ticket can likely be tested.

**Comment by kerstarno** [comment]
> @kerstarno I think it would be easiest to have separate tickets for the changes (from EAC-CPF 2) that are required at this point, since many of the data models where these place elements are listed on the checklists are now no more (e.g., chronItem). I can take a shot at adding the new placeType element, though, along with re-purposing relationType outside of relation. Once I've done that, this ticket can likely be tested.

Yes, definitely. That's the idea anyway. I've mainly included notes for EAC-CPF as a reminder for when the separate issues will be created.

**Comment by kerstarno** [comment]
Tested with the XSD and RNG and can confirm that the above changes have been implemented.
