### ISSUE TITLE
Add @localTypeDeclarationReference to all elements with @localType

### ISSUE THREAD

**Issue by kerstarno** [SAA-SDT/eas-schemas#43]
## Creator of issue

1. Kerstin Arnold
2. EAD team lead, TS-EAS
3. @kerstarno
4. kerstin.arnold@archivesportaleurope.net

## The issue relates to

- [ ] EAC-CPF schema issue
- [ ] EAC-CPF Tag Library issue
- [x] EAD schema issue
- [x] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature

* Text: Add `@localTypeDeclarationReference` as an optional attribute to all elements with `@localType`. `@localTypeDeclarationReference` is of data type IDREFS.

**Update (5 January 2024):
Following the EAD team's meeting on 15 December, the details of this issue have been updated to the latest status. The current development version of the schema might still represent what was outlined initially, while further changes might be necessary and require another round of testing.**

_**Note for working on and testing this issue: When the schema changes are done in development branch, please this by ticking the box on the higher level (printed in bold); once the changes have been tested successfully please mark this by ticking the box on the lower level.**_  

- [x] **Add `@localTypeDeclarationReference` to:**
  - [x] For sub-elements of `<control>` see #32 
  - [x] `<archDesc>`
  - [x] `<abstract>`
  - [x] `<container>`
  - [x] ~~`<dao>`~~ (will become `<formAvailable>`, which includes `@localType` and `@localTypeDeclarationReference`, see #65)
  - [x] ~~`<daoSet>`~~ (same as for `<dao>`)
  - [x] ~~`<didNote>`~~ renamed: `<identificationDataNote>`
  - [x] `<materialSpec>`
  - [x] `<physDesc>`
  - [x] `<physLoc>`
  - [ ] ~~`<origination>`~~ (will become `<agent>`, which includes `@localType` and `@localTypeDeclarationReference`, see #58)
  - [ ] ~~`<repository>`~~ (same as for `<origination>`)
  - [x] `<unitTitle>`
  - [x] `<unitId>`
  - [x] `<accessConditions>`
  - [x] `<accruals>`
  - [x] ~~`<acquinfo>`~~ renamed: `<sourceOfAcquisition>`
  - [x] ~~`<altFormAvail>`~~ (will become `<formAvailable>`, which includes `@localType` and `@localTypeDeclarationReference`, see #65)
  - [x] `<appraisal>`
  - [x] `<arrangement>`
  - [x] `<bibliography>` (renamed to `<publicationNote>`, see #66)
  - [x] `<biogHist>`
  - [x] `<controlAccess>` (renamed to `<subjectHeadings>`, see #67)
  - [x] `<custodHist>`
  - [x] `<filePlan>`
  - [x] ~~`<index>`~~ (incorporated with `<subjectHeadings>`, see #67)
  - [x] `<legalStatus>`
  - [x] ~~`<odd>`~~ renamed: `<otherDescriptiveInfo>`
  - [x] ~~`<originalsLoc>`~~ (will become `<formAvailable>`, which includes `@localType` and `@localTypeDeclarationReference`, see #65)
  - [x] `<otherFindAid>`
  - [x] ~~`<physTech>`~~ renamed: `<physicalOrTechnicalRequirements>`
  - [x] `<preferCite>`
  - [x] `<processInfo>`
  - [x] `<relatedMaterial>`
  - [x] `<scopeContent>`
  - [x] `<separatedMaterial>`
  - [x] `<useConditions>`
  - [ ] ~~`<corpName>`~~ (will become `<agent>`, which includes `@localType` and `@localTypeDeclarationReference`, see #58)
  - [ ] ~~`<famName>`~~ (same as for `<corpName>`)
  - [x] `<function>`
  - [x] ~~`<genreForm>`~~ (will be incorporated with `<subject>` under `<subjectHeadings>`, see #67)
  - [ ] ~~`<name>`~~ (will become `<agent>`, which includes `@localType` and `@localTypeDeclarationReference`, see #58)
  - [x] ~~`<occupation>`~~ (will be incorporated with `<subject>` under `<subjectHeadings>`, see #67)
  - [ ] ~~`<persName>`~~ (will become `<agent>`, which includes `@localType` and `@localTypeDeclarationReference`, see #58)
  - [x] `<placeName>` (as replacement of `<geogname>`, see #42)
  - [x] `<subject>`
  - [x] `<title>`
  - [ ] ~~`<chronList>`~~ (see #62)
  - [ ] ~~`<chronItem>`~~ (see #62)
  - [ ] ~~`<event>`~~ (see #62)
  - [x] `<dimensions>`
  - [x] `<physFacet>`
  - [ ] ~~`<footNote>`~~ (see #63)
  - [x] `<dateRange>`
  - [x] `<fromDate>`
  - [x] `<toDate>`
  - [x] `<dateSet>`
  - [x] `<date>`
  - [ ] ~~`<num>`~~ (see #63)
  - [ ] ~~`<quote>`~~ (see #63)
  - [x] No `@localType` anymore in `<addressLine>` (see #1) nor in `<relations>` (see #33) nor in `<relationentry>` (see #1 and #33) nor in `<datesingle>` (removed, see #4)

**Comment by fordmadox** [comment]
I also had the localType pair added to the new `functions` element, since I think that was mentioned in another ticket... though it's not noted above.  Anyhow, I've done a first pass. Let me know what else needs to change.

**Comment by fordmadox** [comment]
Ahh... the reason I added the localType pair to functions was to align with EAC. I did the same for the rest of the new plural elements, like agents (though not listed above). Let me know if any of those attributes should be removed. If so, then we'll also need EAC-related tickets eventually.

**Comment by kerstarno** [comment]
> Why would `archdesc` get these two attributes but `c` wouldn't?

Because `<archdesc>` already has `@localtype` in EAD3, while the numbered and unnumbered `<c>` elements don't. If there is a request and suitable use case to add `@localType` also to the latter that could be discussed, but we haven't had it so far. 

Thanks for taking care of `<functions>` - that slipped through the net.

**Comment by kerstarno** [comment]
Tested with the XSD and the RNG and can confirm that this has been implemented as expected with the only exception of `<agent>`, which is currently missing `@localType` and `@localTypeDeclarationReference`. However, I will report this in #58, so this issue here can be marked as "Tested successfully".
