### ISSUE TITLE
Remove @entityref and @xpointer from EAD

### ISSUE THREAD

**Issue by kerstarno** [SAA-SDT/eas-schemas#45]
## Creator of issue

1. Kerstin Arnold
2. EAD team lead, TS-EAS
3. @kerstarno
4. kerstin.arnold@archivesportaleurope.net

## The issue relates to

- [ ] EAC-CPF schema issue
- [ ] EAC-CPF Tag Library issue
- [x] EAD schema issue
- [x] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature

* Text: Remove `@entityref` and `@xpointer` from EAD    

**_Note for working on and testing this issue: When the schema changes are done in development branch, please mark this by ticking the box for the higher level in the list (printed in bold); once the changes have been tested successfully please mark this by ticking the box._**

- [x] **Remove `@entityref` from**
  - [ ] ~~`<dao>`~~ (integrated with `<formAvailable>`, see #65)
  - [ ] ~~`<ptr>`~~ (combined with `<reference>`, see #63)
  - [x] `<ref>` (now `<reference>`, see #40)
- [x] **Remove `@xpointer` from**
  - [ ] ~~`<dao>`~~ (integrated with `<formAvailable>`, see #65)
  - [ ] `~~`<ptr>`~~ (combined with `<reference>`, see #63)
  - [x] `<ref>` (now `<reference>`, see #40)

**Comment by kerstarno** [comment]
Thanks, Mark. As a note, but we can discuss later how to best do this: this issue was meant for the EAD Schema (optional attributes) - see label -, which would be one of the alternative schemas to discuss at the Washington meeting - see milestone. I.e. the EAD Schema (general) should, for now, still have `@entityRef` and `@xPointer`, while they should be removed in the EAD Schema (optional attributes).

**Comment by kerstarno** [comment]
TS-EAS has decided to move forward with this issue when discussing it at the EAD revision meeting in Washington, DC, on 24 July 2023.

**Comment by kerstarno** [comment]
Tested with the XSD and the RNG and can confirm that the above has been implemented as expected.
