### ISSUE TITLE
Align content model of <legalStatus> with EAC-CPF 2.0 and move it into <did>

### ISSUE THREAD

**Issue by kerstarno** [SAA-SDT/eas-schemas#5]
## Creator of issue

1. Kerstin Arnold
2. TS-EAS EAD team lead
3. @kerstarno
4.

## The issue relates to

- [ ] EAC-CPF schema issue
- [ ] EAC-CPF Tag Library issue
- [x] EAD schema issue
- [x] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature
* Text: Review the use of `<legalStatus>` as either an informal descriptive element (current EAD3 approach) or a term-based element (current EAC-CPF approach). Would - with the current status of the revision - include the following sub-elements at the moment: `<abstract>`, `<blockQuote>`, `<chronList>`, `<head>`, `<list>`, `<p>`, and `<table>`. Examples in the tag library don't really merit more than a `<descriptiveNote><p>` at the moment.
* Consider alternative encoding along the lines of EAC-CPF:
```
  <legalStatus>
    <term>Student records</term>
    <descriptiveNote>
      <p>Federal, state and local laws apply, as follows.</p>
      <p>Here: Student records are governed by the Family Educational Rights and Privacy Act 
      (FERPA), 20 U.S.C. § 1232g.</p>
    </descriptveNote>
    <date standardDate="1974-08-21">August 21, 1974</date>
    <placeName>United States of America</placeName>
  </legalStatus>
  <legalStatus>
    <term>Patient records</term>
    <descriptiveNote>
      <p>Federal, state and local laws apply, as follows.</p>
      <p>Here: Patient records are governed by the Health Insurance Portability and Accountability
      Act, Pub.L. 104–191 and 110 Stat. 1936. Article 8 ECHR may also apply.</p>
    </descriptiveNote>
  </legalStatus>
```
Could maybe become a new sub-element of `<did>` with a similar content model to `<languageOfMaterial>`, i.e. `<descriptiveNote>` (which - via `<p><reference>` - would include an option to point to an external resource), the set of date elements, a `<placeName>`  and `<term>`.

**Comment by kerstarno** [comment]
The EAD sub-team discussed `<legalStatus>` during their meeting on 24 November 2023 and again during their meeting on 15 December 2023, the second time as a side note in the more general context of discussing relations in EAD, and has taken the following decision: 

* `<legalStatus>` is a basis/precondition that results in certain access and use conditions, i.e. having it as separate element as in EAD3 makes sense
* As it is a shared element between EAD and EAC-CPF, the definition of `<legalStatus>` as in EAC-CPF 2.0 should be adopted for EAD 4.0
* As `<legalStatus>` will - as a result of the above - look rather different from the group of elements that it is currently a part of in EAD3, it should be moved into `<identificationData>` (renamed from `<did>`, #66)

_**Note for working on and testing this issue: When the schema changes are done in development branch, please mark the tasks on the highest levels of the list (printed in bold) by ticking the box. When the changes have been tested successfully, please mark the tasks on the lowest level of the list.**_ 

- [ ] **Adapt `<legalStatus>` to the definition used in EAC-CPF 2.0**
  - [ ] Apply camelCase to `<legalStatus>`
  - [ ] Move `<legalStatus>` into `<identificationData>`
  - [ ] Have it as optional and repeatable sub-element of `<identificationData>`
  - [ ] Add `<term>` as a required and repeatable sub-element of `<legalStatus>`
  - [ ] Add a choice between `<date>`, `<dateRange>` or `<dateSet>` to `<legalStatus>` (optional, not repeatable)
  - [ ] Add `<placeName>` as an optional and repeatable sub-element to `<legalStatus>`
  - [ ] Remove `<head>` from `<legalStatus>` (would have been the case as well if kept outside of `<identificationData>`, #62)
  - [ ] Remove `<blockquote>`, `<chronlist>`, `<list>`, <p>`, and `<table>` from `<legalStatus>` (would have been the case as well if kept outside of `<identificationData>`, #62) 
  - [ ] Add `<descriptiveNote>` instead as an optional, not repeatable sub-element of `<legalStatus>`
  - [ ] Remove nesting from `<legalStatus>`(would have been the case as well if kept outside of `<identificationData>`, #59)
  - [ ] Adapt `@audience`
  - [ ] Remove `@altrender`
  - [ ] Rename `@lang` to `@languageOfElement` and `@script` to `@scriptOfElement`
  - [ ] Remove `@encodinganalog`
  - [ ] Apply camelCase to `@localType` and add the optional `@localTypeDeclarationReference`
  - [ ] Add the optional attributes `@vocabularySource`, `@vocabularySourceURI`, `@valueURI`, `@maintenanceEventReference`, `@sourceReference`, and `@conventionDeclarationReference`
  - [ ] Add an option to include attributes from any other namespace

**Comment by kerstarno** [comment]
@marieelia - mainly added you for information. There are (currently) no changes for EAC-CPF resulting from this issue.

**Comment by fordmadox** [comment]
Should be good to test, but why not keep the legalStatuses wrapped from EAC (making the two interchangeable), and then promote legalStatuses to live side-by-side with agents, functions, etc.???

**Comment by kerstarno** [comment]
`<agent>`, `<function>`, and `<formAvailable>` represent related entities in themselves - rather than describing the archival materials and their characteristics directly. Hence they get an elevated status by defining a dedicated space for them and by grouping them with the plural elements. 

Sure, one could argue that `<legalStatus>` represents a rule and thereby an entity as well, but during their conversations the EAD team felt like `<legalStatus>` is still more a characteristic of the archival material resulting e.g. in specific conditions for access and use. Hence the inclusion in `<identificationData>` and applying the same approach as for other sub-elements of that in simply repeating the singular element. 

It would still be possible to copy multiple `<legalStatus>` elements from an EAD file into a `<legalStatuses>` element in EAC-CPF, based on the singular element being defined the same in both standards.

**Comment by kerstarno** [comment]
Tested with the XSD and the RNG and can confirm that all the changes outlined above have been implemented.
