### ISSUE TITLE
Review the use of the new element <formattingExtension> also for EAC-CPF; here: encoding of chronological lists

### ISSUE THREAD

**Issue by kerstarno** [SAA-SDT/eas-schemas#56]
## Creator of issue

1. Kerstin Arnold
2. EAD team lead, TS-EAS
3. @kerstarno
4. kerstin.arnold@archivesportaleurope.net

## The issue relates to

- [x] EAC-CPF schema issue
- [x] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [ ] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature

* Text: The encoding of chronological lists needs to be aligned again across both EAS. 

_**Note for working on and testing this issue: When the schema changes are done in development branch, please mark the tasks on the highest levels of the list (printed in bold) by ticking the box. When the changes have been tested successfully, please mark the tasks on the lowest level of the list.**_ 

- [x] **`<chronList>`**
  - [ ] Apply camelCase spelling to `<chronList>` and its required and repeatable sub-element `<chronItem>`
  - [ ] Remove `<head>` and `<listhead>`
  - [ ] Adapt `@audience`
  - [ ] Add `@target`
  - [ ] Rename `@lang` and `@script` to `@languageOfElement` and `@scriptOfElement` respectively
  - [ ] Apply camelCase spelling to `@localType>`
  - [ ] Add `@localTypeDeclarationReference`
  - [ ] Add `@conventionDeclarationReference`, `@mainetancenEventReference`, and `@sourceReference`
  - [ ] Add an option to include attributes from any other namespace
- [x] **`<chronItem>`**
  - [ ] Apply camelCase spelling also to sub-elements `<dateRange>`, `<dateSet>`, and `<chronItemSet>`
  - [ ] Replace `<datesingle>` with `<date>` (see #4)
  - [ ] Replace `<geogname>` with `<place>` (optional, not repeatable, see #42) and put it after `<event>`
  - [ ] Add `<reference>` as optional and repeatable (see #40)
  - [ ] Adapt `@audience`
  - [ ] Add `@target`
  - [ ] Rename `@lang` and `@script` to `@languageOfElement` and `@scriptOfElement` respectively
  - [ ] Apply camelCase spelling to `@localType>`
  - [ ] Add `@localTypeDeclarationReference`
  - [ ] Add `@conventionDeclarationReference`, `@mainetancenEventReference`, and `@sourceReference`
  - [ ] Add an option to include attributes from any other namespace
- [x] **`<event>`**
  - [ ] Rename `<ref>` to `<reference>` 
  - [ ] Add `<span>` (as optional and repeatable)
  - [ ] Adapt `@audience`
  - [ ] Add `@target` 
  - [ ] Rename `@lang` and `@script`to `@languageOfElement` and `@scriptOfElement` respectively 
  - [ ] Add `@conventionDeclarationReference`, `@maintenanceEventReference`, and `@sourceReference` 
  - [ ] Add `@localTypeDeclarationReference` 
  - [ ] Add `@valueURI`, `@vocabularySource`, and `@vocabularySourceURI`
  - [ ] Add an option to include attributes from any other namespace
- [x] **`<chronItemSet>`**
  - [ ] Replace `<geogname>` with `<place>` (optional, repeatable, see #42) and put it after `<event>`
  - [ ] Add `<reference>` as optional and repeatable (see #40)
  - [ ] Adapt `@audience`
  - [ ] Add `@target`
  - [ ] Rename `@lang` and `@script` to `@languageOfElement` and `@scriptOfElement` respectively
  - [ ] Add `@conventionDeclarationReference`, `@mainetancenEventReference`, and `@sourceReference`
  - [ ] Add an option to include attributes from any other namespace

**Comment by kerstarno** [comment]
Needs another look in light of https://github.com/SAA-SDT/eas-schemas/issues/62

**Comment by fordmadox** [comment]
Do lists get superseded by the "formattingExtention" element?  If not, this is ready for testing.  If so, then I think we just need a list of available XHTML elements to permit in that new wrapper (if we're going to validate that extension?).

**Comment by kerstarno** [comment]
With the suggested introduction of the element `<formattingExtension>`, chronological lists indeed would not be part of the EAD 4.0 schema anymore. Instead, `<formattingExtension>` would allow for the encoding of lists by using the relevant XHTML namespace and elements (see #62 for details of suggested XHTML elements).

@marieelia - leaving this issue open as a review issue for EAC-CPF at a later stage as part of a future major revision.

**Comment by MicheleCombs** [comment]
I may be too late with this comment, or perhaps it’s already been discussed and addressed, but reading over all these changes it seems to me we are “genericizing” an awful lot of EAD.  One of the nice things about EAD has always been that it was mostly self-contained (i.e., it had everything you needed, and you didn’t have to stress over multiple namespaces, and pulling in all kinds of other tag sets) and it was mostly self-explanatory (i.e., the element names actually meant what they were so it was easy to learn and to teach and to use).  I feel like we’re getting away from that and I wonder if that’s a good thing.  Are we (again) falling into the habit of privileging the automated/database approach, and as a side effect making it harder for places that hand-encode their finding aids?

Anyway, just a thought.

Michele

**Comment by kerstarno** [comment]
In this context, also keep #118 in mind for implementation in EAC-CPF for `<biogHist>`.

**Comment by kerstarno** [comment]
With `<formattingExtension>` having been added to EAC-CPF and `<chronList>` and its sub-elements having been replaced by `<narrativeEvent>`, this issue seems obsolete.
