### ISSUE TITLE
Introduce a new <formattingExtension> element as a choice next to <p> to group current formatting elements

### ISSUE THREAD

**Issue by kerstarno** [SAA-SDT/eas-schemas#62]
## Creator of issue

1. Kerstin Arnold
2. TS-EAS EAD team lead
3. @kerstarno 
4. kerstin.arnold@archivesportaleurope.net

## The issue relates to

- [ ] EAC-CPF schema issue
- [ ] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [ ] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [x] Suggestions for all schemas
- [x] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature

* Text: During their meeting on 27 October 2023, the EAD sub-team of TS-EAS confirmed the introduction of a new element called `<formattingExtension>` to enable any formatting of text that goes beyond a simple `<p>` tag. The idea is to add a choice between using just `<p>` and using `<formattingExtension>`, which would have a similar function as the element `<objectXMLWrap>`, but would come with the XHTML namespace predefined and be recommended for use with elements that allow the creation of lists, tables, etc. 
* `<formattingExtension>` would thereby "incorporate" those elements that the EAS initially adapted/borrowed from HTML and bring them back into their original namespace.
* In detail, this means that the EAS' focus would be returned to encoding information rather than encoding how this information is formatted by removing any formatting elements other than `<p>` and `<head>` (when used with the numbered and unnumbered `<c>` elements or `<did>`) from the EAS schemas. 

**_Note for working on and testing this issue: When the schema changes are done in development branch, please mark this by ticking the box for the higher level in the list (printed in bold); once the changes have been tested successfully please mark this by ticking the box on the lower and intermediate (printed in italics) levels._**

- [x] **Add `<formattingExtension>` as a choice next to `<p>` in**
  - [x] `<accessConditions>` (renamed from `<accessrestrict>`, see #60)
  - [x] `<accruals>`
  - [x] ~~`<acqinfo>`~~ renamed to `<sourceOfAcquisition>`
  - [x] `<formAvailable>` (replacing `<altformavail>`, `<originalsloc>`, `<dao>`, and `<daoset>`, see #65)
  - [x] `<appraisal>`
  - [x] `<arrangement>`
  - [x] `<publicationNote>` (renamed from `<bibliography>`, see #66)
  - [x] `<biogHist>`
  - [x] `<subjectHeadings>` (renamed from `<controlaccess>` and incorporating `<index>`, see #67)
  - [x] `<custodHist>`
  - [x] `<descriptionOfComponents`> (renamed from `<dsc>`, see #66) 
  - [x] `<filePlan>`
  - [x] ~~`<odd>`~~ renamed to `<otherDescriptiveInfo>`
  - [x] `<otherFindAid>`
  - [x] ~~`<physTech>`~~ renamed to `<physicalOrTechnicalRequirements>`
  - [x] `<preferCite>`
  - [x] `<processInfo>`
  - [x] `<relatedMaterial>` 
  - [x] `<scopeContent>`
  - [x] `<separatedMaterial>`
  - [x] `<useConditions>` (renamed from `<userestrict>`, see #60)
- [x] **`<formattingExtension>`**
  - [x] Requires a reference to the XHTML namespace
  - [x] Can then be used with any XHTML elements like `<h1>` to `<h6>`, `<blockquote>`, `<p>`, different types of lists (`<dl>`, `<ol>`, `<ul>`), `<table>`, `<div>` and others
  - [x] Allows for the optional attributes `@audience`, `@id`, and `@target` (same as `<objectXMLWrap>`)
- [x] **Remove `<blockquote>`, `<chronList>`, `<list>`, and `<table>` with all their sub-elements and attributes from**  
  - [x] `<accessConditions>` (renamed from `<accessrestrict>`, see #60)
  - [x] `<accruals>`
  - [x] ~~`<acqinfo>`~~ renamed to `<sourceOfAcquisition>`
  - [x] `<formAvailable>` (replacing `<altformavail>`, `<originalsloc>`, `<dao>`, and `<daoset>`, see #65)
  - [x] `<appraisal>`
  - [x] `<arrangement>`
  - [x] `<publicationNote>` (renamed from `<bibliography>`, see #66)
  - [x] `<biogHist>`
  - [x] `<subjectHeadings>` (renamed from `<controlaccess>` and incorporating `<index>`, see #67)
  - [x] `<custodHist>`
  - [x] `<descriptionOfComponents`> (renamed from `<dsc>`, see #66) 
  - [x] `<filePlan>`
  - [x] ~~`<odd>`~~ renamed to `<otherDescriptiveInfo>`
  - [x] `<otherFindAid>`
  - [x] ~~`<physTech>`~~ renamed to `<physicalOrTechnicalRequirements>`
  - [x] `<preferCite>`
  - [x] `<processInfo>`
  - [x] `<relatedMaterial>` 
  - [x] `<scopeContent>`
  - [x] `<separatedMaterial>`
  - [x] `<useConditions>` (renamed from `<userestrict>`, see #60)
- [x] **With the previous step, these elements `<blockquote>`, `<chronList>`, `<list>`, and `<table>` with any sub-elements and attributes that are only used in their context will be removed from EAD. This refers to the following:**
  - [x] `<blockquote>`
  - [x] `<chronList>`
  - [x]  `<chronItem>`
  - [x] `<event>`
  - [x] `<chronItemSet>`
  - [x] `<listhead>`
  - [x] `<head01>`
  - [x] `<head02>`
  - [x] `<head03>`
  - [x] `<list>`
  - [x] `<defitem>`
  - [x] `<item>`
  - [x] `<label>`
  - [x] `<table>`
  - [x] `<tgroup>`
  - [x] `<colspec>`
  - [x] `<thead>`
  - [x] `<tbody>`
  - [x] `<row>`
  - [x] `<entry>`
  - [x] `@listtype`
  - [x] `@mark`
  - [x] `@numeration`
  - [x] `@colsep`
  - [x] `@frame`
  - [x] `@pgwide`
  - [x] `@rowsep`
  - [x] `@align`
  - [x] `@cols`
  - [x] `@char`
  - [x] `@charoff`
  - [x] `@colname`
  - [x] `@colnum`
  - [x] `@colwidth`
  - [x] `@valign`
  - [x] `@morerows`
  - [x] `@nameend`
  - [x] `@namest`
- [x] **Remove `<head>` from**  
  - [x] `<accessConditions>` (renamed from `<accessrestrict>`, see #60)
  - [x] `<accruals>`
  - [x] ~~`<acqinfo>`~~ renamed to `<sourceOfAcquisition>`
  - [x] `<formAvailable>` (replacing `<altformavail>`, `<originalsloc>`, `<dao>`, and `<daoset>`, see #65)
  - [x] `<appraisal>`
  - [x] `<arrangement>`
  - [x] `<publicationNote>` (renamed from `<bibliography>`, see #66)
  - [x] `<biogHist>`
  - [x] `<subjectHeadings>` (renamed from `<controlaccess>` and incorporating `<index>`, see #67)
  - [x] `<custodHist>`
  - [x] `<descriptionOfComponents`> (renamed from `<dsc>`, see #66) 
  - [x] `<filePlan>`
  - [x] ~~`<odd>`~~ renamed to `<otherDescriptiveInfo>`
  - [x] `<otherFindAid>`
  - [x] ~~`<physTech>`~~ renamed to `<physicalOrTechnicalRequirements>`
  - [x] `<preferCite>`
  - [x] `<processInfo>`
  - [x] `<relatedMaterial>` 
  - [x] `<scopeContent>`
  - [x] `<separatedMaterial>`
  - [x] `<useConditions>` (renamed from `<userestrict>`, see #60)

_For changes to `<legalStatus>` see #5._
_For changes regarding `<footnote>` see #63._

**Comment by fordmadox** [comment]
Just a note that I still need to work on this.  I'm unclear if we're going to try to validate a subset of XHTML, or just treat this element like objectXMLWrap in a specific namespace?

**Comment by kerstarno** [comment]
> Just a note that I still need to work on this. I'm unclear if we're going to try to validate a subset of XHTML, or just treat this element like objectXMLWrap in a specific namespace?

Ideally, we would want to validate a subset of XHTML included in `<formattingExtension>`, i.e. the element should require a reference to the XHTML namespace as e.g. `<dao>` used to in EAD 2002 when used with XLink attributes.

**Comment by kerstarno** [comment]
For a high-level conversion route (details will follow at a later stage) of the current block elements in EAD3: 
* `<blockquote>`, `<p>`, and `<table>` would become their equivalents in XHTML
* `<list>` would become
  * `<dl>` when used with the `@listtype="deflist"` and/or with the sub-element `<defitem>`
  * `<ol>` when used with the `@listtype="ordered"` and/or with the attribute `@numeration`
  * `<ul>` when used with the `@listtype="unordered"` and/or with the attribute `@mark`
  * `<ul>` when used without any indicating attributes or sub-elements
* `<chronlist>` would be transformed into
  * `<dl>` when used only with `<chronitem>`, one of the date elements and `<event>`
  * a `<table>` with three columns when used only with `<chronitem>`, one of the date elements, `<event>`, and `<geogname>`
  * a `<table>` with four or more columns when used with `<chronitem>` including `<chronitemset>`(with one or more `<event>` and possibly one or more `<geogname>` elements) plus one of the date elements

**Comment by kerstarno** [comment]
@marieelia - Adding you for information at the moment as this change might then also be applied to EAC-CPF at a later stage. I've currently categorised this as a major revision item.

**Comment by fordmadox** [comment]
@kerstarno :  will this element also appear in `descriptiveNote`?

**Comment by fordmadox** [comment]
Also note that I'm not yet forcing an HTML namespace prefix, but any elements in that namespace can currently be utilized here.

**Comment by kerstarno** [comment]
> @kerstarno : will this element also appear in `descriptiveNote` and (the element previously known as) `didNote`? Or, as I suspect, are those holdover note fields the exclusive domain of EAS description rather than HTML extension?

No, indeed, `<descriptiveNote>` and `<identificationDataNote>` remain just with `<p>`.

**Comment by kerstarno** [comment]
With regard to XHTML in `<formattingExtension>`, I can confirm that I can use any elements in `<formattingExtension>` and that the XHTML namespace declaration is currently not forced. In testing I created the following example using the selection of elements mentioned above:
```
<biogHist>
   <formattingExtension xmlns:xhtml="http://www.w3.org/1999/xhtml">
      <xhtml:h1></xhtml:h1>
      <xhtml:h2></xhtml:h2>
      <xhtml:h3></xhtml:h3>
      <xhtml:dl></xhtml:dl>
      <xhtml:ul></xhtml:ul>
      <xhtml:ol></xhtml:ol>
      <xhtml:table></xhtml:table>
      <xhtml:p></xhtml:p>
      <xhtml:blockquote></xhtml:blockquote>
      <xhtml:div></xhtml:div>
   </formattingExtension>
</biogHist>
```

In the test file validating against the XSD, Oxygen does not suggest any sub-elements, e.g. for the lists or the table element, neither from XHTML, nor EAD. In the test file validating against the RNG, however, Oxygen suggests EAD elements as possible sub-elements of the XHTML elements. 

The latter case should definitely be avoided, so a stricter binding to the XHTML namespace might be required here.

**Comment by kerstarno** [comment]
Additionally, and apologies that I am only realising now that this was not specified before:  `<formattingExtension>` should not be repeatable. I.e. there'd be the choice between either a single `<formattingExtension>` (within which all XHTML elements could then be repeated) or a repeatable `<p>` element. I created another pull request (#82) for this.

**Comment by fordmadox** [comment]
Regarding the above example, the "formattingExtension" element itself would still need to be in the EAD4 / EAS (if we converge to one namespace, which I think we can) namespace.  Alternatively a custom element by that name could be defined for HTML, but I don't know how that would work with how we currently manage our tag library, etc.  

Anyhow, I'm going to keep the "Needs More Work" label on this issue for the time being while we work out the validation process for this extension.

**Comment by kerstarno** [comment]
> Regarding the above example, the "formattingExtension" element itself would still need to be in the EAD4 / EAS (if we converge to one namespace, which I think we can) namespace. Alternatively a custom element by that name could be defined for HTML, but I don't know how that would work with how we currently manage our tag library, etc.
> 
> Anyhow, I'm going to keep the "Needs More Work" label on this issue for the time being while we work out the validation process for this extension.

Ah, yes, true. My mistake - misread and misadapted the encoding used for `<objectXMLWrap>` in the EAC-CPF 2.0 TL... Thanks for the clarification.

**Comment by kerstarno** [comment]
As an interim test report: the choice between `<formattingExtension>` and `<p>` is now also available in `<descriptionOfComponents>` in both, the XSD and the RNG. 

However, there's now a difference between the two schema versions:  
- In the RNG, it is correct - `<formattingExtension>` is not repeatable, while `<p>` is and both are optional. 
- In the XSD, on the other hand, `<formattingExtension>` can still be repeated, which should only be possible within `<findAidDesc>`, but not when used next to `<p>`.

**Comment by fordmadox** [comment]
Note: I've updated this as ready for testing due to updates for the XHTML embedding features being supported now, but I haven't yet the availability issue noted above.  I'll keep this issue with labels of both 'ready for testing' and 'needs more work' to cover both features.

**Comment by fordmadox** [comment]
Note:  I've pushed a quick fix of the RNG + XSD difference regarding the availability of this element within the former `dsc` and related elements.  Should be good to test again.  

Another note:  See issue 100.  I think there is another issue with the RNG / NVDL combo.  Won't have time to investigate until after the call for comments goes out, so just an FYI (and why we'll continue to hit the XSD version of the schema in the NVDL file).

**Comment by kerstarno** [comment]
Retested with XSD and RNG and can confirm, that an choice between `<formattingExtension>` and `<p>` is now available with `<descriptionOfComponents>` and elements such as `<scopeContent>`, `<biogHist>` etc. Both elements are optional, `<p>` can be repeated, `<formattingExtension>` cannot be repeated. 

The only context in which `<formattingExtension>` is (correctly) repeatable is `<findAidDesc>`. 

For validation against the XHTML namespace see the NVDL file under https://github.com/SAA-SDT/eas-schemas/tree/development/xml-schemas/ead
