### ISSUE TITLE
Rename certain elements for better alignment with ISAD(G), DACS, etc. respectively for being better understandable

### ISSUE THREAD

**Issue by kerstarno** [SAA-SDT/eas-schemas#66]
## Creator of issue

1. Kerstin Arnold
2. EAD team lead, TS-EAS
3. @kerstarno
4. kerstin.arnold@archivesportaleurope.net

## The issue relates to

- [ ] EAC-CPF schema issue
- [ ] EAC-CPF Tag Library issue
- [x] EAD schema issue
- [x] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature

* Text: As part of the major revision, certain elements are to be renamed for better alignment with ISAD(G), DACS, and other standards respectively for being better understandable, especially with regard to the international user community of the EAS. This goes along with applying camel casing to EAD (#49), which already requires a "renaming" of some kind for element names consisting of two or more parts, and with a review of abbreviated element names (#53), which will be of help for non-native speakers of English. Some of these renamings are already accounted for in other issues, which will be indicated in the list below. 

_**Note for working on and testing this issue: When the schema changes are done in development branch, please mark the tasks on the highest levels of the list (printed in bold) by ticking the box. When the changes have been tested successfully, please mark the tasks on the lowest level and - if applicable - the intermediate levels (printed in italics) of the list.**_ 

- [x] **Rename the following elements**  
  - [x] `<accessrestrict>` to `<accessConditions>` (#60)
  - [x] `<acqinfo>` to `<sourceOfAquisition>`
  - [x] `<bibliography>` to `<publicationNote>`
  - [x] _`<did>` to `<identificationData>`_
    - [x] `<didNote>` to `<identificationDataNote>` 
  - [x] _`<dsc>` to `<descriptionOfComponents>`_
    - [x] `@dsctype` to `@descriptionOfComponentsType`
    - [x] `@dscTypeEncoding` to `@descriptionOfComponentsTypeEncoding` with values “EASList” and - now - “otherDescriptionOfComponentsTypeEncoding” (#1)
  - [x] `<langmaterial>` to `<languageOfMaterial>`
  - [x] `<odd>` to `<otherDescriptiveInfo>`
  - [x] `<phystech>` to `<physicalOrTechnicalRequirements>`
  - [x] `<ref>` to `<reference>` (#40)
  - [x] `<script>` to `<writingSystem>` (#38, also aligning with EAC-CPF)
  - [x] `<userestrict>` to `<useConditions>` (#60)

**Comment by kerstarno** [comment]
These renamings have been suggested ahead of the EAD sub-team meeting on 15 December 2023 and are currently undergoing final confirmation by the team. 

@fordmadox - the deadline for the team to confirm is 10 January. I'll leave it to you if you'd already want to include these name changes or wait until then.

**Comment by kerstarno** [comment]
These re-namings have now been confirmed via virtual conversation within the EAD sub-team. The changes as defined above can be implemented.

**Comment by deletedname** [comment]
Tested in XSD and RNG. Found that `<langMaterial>` should be `<languageOfMaterial>` in both schema files. @fordmadox

**Comment by deletedname** [comment]
Testing in RNG and XSD for `<languageOfMaterial>` is successful
