### ISSUE TITLE
Rename <controlaccess> to <subjectHeadings> and combine with <index>

### ISSUE THREAD

**Issue by kerstarno** [SAA-SDT/eas-schemas#67]
## Creator of issue

1. Kerstin Arnold
2. EAD team lead, TS-EAS
3. @kerstarno
4. kerstin.arnold@archivesportaleurope.net

## The issue relates to

- [ ] EAC-CPF schema issue
- [ ] EAC-CPF Tag Library issue
- [x] EAD schema issue
- [x] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature

* Text: As part of their conversations on the use of relations in EAD throughout the whole revision process, the EAD sub-team also discussed the use of the elements `<controlaccess>` and `<index>` at various occasions. During their meeting on 15 December, the EAD sub-team decided to ensure these elements are - also from the encoding point of view - more specifically focussed on content rather than context and concentrate on the aspect of “about-ness” (independent of whether the entity that the materials are about is a person, place, or concept, etc.). The suggestion resulting from this is to rename `<controlaccess>` and call it more explicitly `<subjectHeadings>` and to combine `<index>` with this new element as well. 

_**Note for working on and testing this issue: When the schema changes are done in development branch, please mark the tasks on the highest levels of the list (printed in bold) by ticking the box. When the changes have been tested successfully, please mark the tasks on the lowest level and - if applicable - the intermediate levels (printed in italics).**_ 

- [ ] **Add a new element `<subjectHeadings>` as optional and repeatable sub-element of `<archDesc>` and the numbered and unnumbered `<c>` elements**
  - [ ] Enable a choice between `<p>` and `<formattingExtension>` as optional sub-elements of `<subjectHeadings>`
  - [ ] _Enable `<subject>` as an optional and repeatable sub-element of `<subjectHeadings>`_
    - [ ] Have `<term>` as a required and repeatable sub-element of `<subject>`
    - [ ] Remove `<part>` as a required and repeatable sub-element of `<subject>`
    - [ ] Allow for `<targetType>`, `<targetRole>`, and `<relationType>` as optional and repeatable sub-elements of `<subject>` (see #33 for the definition of these three elements)
    - [ ] Enable an optional choice between `<date>`, `<dateRange>`, or `<dateSet>` as sub-element of `<subject>`
    - [ ] Allow for `<placeName>` as an optional and repeatable sub-element of `<subject>`
    - [ ] Allow for `<descriptiveNote>` as an optional, not repeatable sub-element of `<subject>`
    - [ ] Adapt the use of `@audience`
    - [ ] Add `@target` as an optional attribute
    - [ ] Rename `@lang` to `@languageOfElement` and `@script` to `@scriptOfElement`
    - [ ] Remove `@altrender` and `@encodinganalog`
    - [ ] Apply camelCase spelling to `@localType` and add `@localTypeDeclarationReference`
    - [ ] Replace `@source` with `@vocabularySource` and add `@vocabularySourceURI`
    - [ ] Replace `@identifier` with `@valueURI`
    - [ ] Add the optional attributes `@maintenanceEventReference`, `@sourceReference`, and `@conventionDeclarationReference`
    - [ ] Remove `@relator` (replaced by `<targetRole>`, see above)
    - [ ] Allow for attributes from any other namespace in `<subject>`
  - [ ]  Allow for the optional attributes of `@audience`, `@id`, `@target`, `@languageOfElement`, `@scriptOfElement`, `@localType`, `@localTypeDeclarationReference`, `@maintenanceEventReference`, `@sourceReference`, and `@conventionDeclarationReference` in `<subjectHeadings>`
  - [ ] Allow for attributes from any other namespace in `<subjectHeadings>`
  - [ ] Remove `<controlaccess>` and `<index>` from EAD
    - [ ] Remove `<indexentry>`, `<namegrp>`, and `<ptrgrp>` from EAD
    - [ ] For `<corpname>`, `<famname>`, `<name>` and `<persname>` as sub-elements of `<controlaccess>` and `<index>` see #58
    - [ ] For `<geogname>` as sub-element of `<controlaccess>` and `<index>` see #42 
    - [ ] For `<function>` as sub-element of `<controlaccess>` and `<index>` see #61

**Comment by MicheleCombs** [comment]
Not sure what is meant by “combine index with this new element as well” – does this mean that the index element is going away?

Michele

From: Kerstin Arnold ***@***.***>
Sent: Wednesday, December 20, 2023 10:59 AM
To: SAA-SDT/eas-schemas ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [SAA-SDT/eas-schemas] Rename <controlaccess> to <subjectHeadings> and combine with <index> (Issue #67)

Creator of issue

  1.  Kerstin Arnold
  2.  EAD team lead, TS-EAS
  3.  @kerstarno<https://github.com/kerstarno>
  4.  ***@***.******@***.***>

The issue relates to

  *   [ ] EAC-CPF schema issue
  *   [ ] EAC-CPF Tag Library issue
  *   [X] EAD schema issue
  *   [X] EAD Tag Library issue
  *   [ ] Schema issue
  *   [ ] Tag Library issue
  *   [ ] Suggestions for all schemas
  *   [ ] Suggestions for all Tag Libraries
  *   [ ] Other

Wanted change/feature

  *   Text: As part of their conversations on the use of relations in EAD throughout the whole revision process, the EAD sub-team also discussed the use of the elements <controlaccess> and <index> at various occasions. During their meeting on 15 December, the EAD sub-team decided to ensure these elements are - also from the encoding point of view - more specifically focussed on content rather than context and concentrate on the aspect of “about-ness” (independent of whether the entity that the materials are about is a person, place, or concept, etc.). The suggestion resulting from this is to rename <controlaccess> and call it more explicitly <subjectHeadings> and to combine <index> with this new element as well.

Note for working on and testing this issue: When the schema changes are done in development branch, please mark the tasks on the highest levels of the list (printed in bold) by ticking the box. When the changes have been tested successfully, please mark the tasks on the lowest level and - if applicable - the intermediate levels (printed in italics).

  *   [ ] Add a new element <subjectHeadings> as optional and repeatable sub-element of <archDesc> and the numbered and unnumbered <c> elements
     *   [ ] Enable a choice between <p> and <formattingExtension> as optional sub-elements of <subjectHeadings>
     *   [ ] Enable <subject> as an optional and repeatable sub-element of <subjectHeadings>
        *   [ ] Have <term> as a required and repeatable sub-element of <subject>
        *   [ ] Remove <part> as a required and repeatable sub-element of <subject>
        *   [ ] Allow for <targetType>, <targetRole>, and <relationType> as optional and repeatable sub-elements of <subject> (see #33<https://github.com/SAA-SDT/eas-schemas/issues/33> for the definition of these three elements)
        *   [ ] Enable an optional choice between <date>, <dateRange>, or <dateSet> as sub-element of <subject>
        *   [ ] Allow for <placeName> as an optional and repeatable sub-element of <subject>
        *   [ ] Allow for <descriptiveNote> as an optional, not repeatable sub-element of <subject>
        *   [ ] Adapt the use of @audience
        *   [ ] Add @target as an optional attribute
        *   [ ] Rename @lang to @languageOfElement and @script to @scriptOfElement
        *   [ ] Remove @altrender and @encodinganalog
        *   [ ] Apply camelCase spelling to @localType and add @localTypeDeclarationReference
        *   [ ] Replace @source with @vocabularySource and add @vocabularySourceURI
        *   [ ] Replace @identifier with @valueURI
        *   [ ] Add the optional attributes @maintenanceEventReference, @sourceReference, and @conventionDeclarationReference
        *   [ ] Remove @relator (replaced by <targetRole>, see above)
        *   [ ] Allow for attributes from any other namespace in <subject>
     *   [ ] Allow for the optional attributes of @audience, @id, @target, @languageOfElement, @scriptOfElement, @localType, @localTypeDeclarationReference, @maintenanceEventReference, @sourceReference, and @conventionDeclarationReference in <subjectHeadings>
     *   [ ] Allow for attributes from any other namespace in <subjectHeadings>
     *   [ ] Remove <controlaccess> and <index> from EAD
        *   [ ] Remove <indexentry>, <namegrp>, and <ptrgrp> from EAD
        *   [ ] For <corpname>, <famname>, <name> and <persname> as sub-elements of <controlaccess> and <index> see #58<https://github.com/SAA-SDT/eas-schemas/issues/58>
        *   [ ] For <geogname> as sub-element of <controlaccess> and <index> see #42<https://github.com/SAA-SDT/eas-schemas/issues/42>
        *   [ ] For <function> as sub-element of <controlaccess> and <index> see #61<https://github.com/SAA-SDT/eas-schemas/issues/61>

**Comment by kerstarno** [comment]
> Not sure what is meant by “combine index with this new element as well” – does this mean that the index element is going away? Michele

That would currently be the suggestion, yes. There's significant indication (NAFAN EAD Data Dashboard, EAD Tag Usage study from 2013, and EAD tag usage across Europe) that `<index>` is used very little to not at all.

**Comment by MicheleCombs** [comment]
That would be a real shame, and I would argue pretty strongly for keeping it.  Indexes are an incredibly useful information-location tool.

We use this element quite a lot for our architecture and cartoon collections and find it extremely helpful for our curators and public services staff, as well as researchers.  Here are two examples:

https://library.syracuse.edu/digital/guides/l/lescaze_w.htm - See “Alphabetical index of projects”

https://library.syracuse.edu/digital/guides/a/alexander_fo.htm - See “Index to cartoons”

I’m not sure what we would replace it with, if the index element was removed.

Michele

**Comment by fordmadox** [comment]
I took at a shot at updating this.  Let me know what else needs to be updated.

**Comment by kerstarno** [comment]
Tested with the XSD and the RNG and can confirm that the changes as described above have been implemented.
